# The Utility and Importance of Creeds and Confessions: Adressed Particularly to Candidates for the Ministry

**by Samuel Miller, D.D.**

*"In necessariis unitas, non necessariis libertas, in omnibus charitas." – Augustine*

The character and situation of one who is preparing for the Sacred Office, are interesting beyond the power of language to express. Such an one, like the Master whom he professes to love and serve, is “set for the fall and rising again of many in Israel.” In all that he is, and in all that he does, the temporal and eternal welfare not only of himself, but of thousands, may be involved. On every side he is beset with perils. Whatever may be his talents and learning, if he have not genuine piety, he will probably be a curse instead of a blessing to the Church. But this is not the only danger to which he is exposed. He may have unfeigned piety, as well as talents and learning; and yet, from habitual indiscretion; from a defect in that sobriety of mind, which is so precious to all men, but especially to every one who occupies a public station; from a fondness for novelty and innovation, or from that love of distinction which is so natural to men;-after all, instead of edifying the “body of Christ,” he may become a disturber of its peace, and a corrupter of its purity; so that we might almost say, whatever may be the result with respect to himself, “it had been good for the Church if he had never been born."

Hence it is, that every part of the character of him who is coming forward to the holy ministry; his opinions; his temper; his attainments; his infirmities; and above all, his character as a practical Christian;—are of inestimable importance to the ecclesiastical community of which he is destined to be a minister. Nothing that pertains to him is uninteresting. If it were possible for him, strictly speaking, to “live to himself,” or to “die to himself,” the case would be different. But it is not possible. His defects as well as his excellencies; his gifts and graces, as well as the weak points of his character, must and will all have their appropriate effect on every thing that he touches. Can you wonder, then, that employed to conduct the education of candidates for this high and holy office, we feel ourselves placed under a solemn, nay, an awful responsibility? Can you wonder that, having advanced a little before you in our experience in relation to this office, we cherish the deepest solicitude at every step you take? Can you wonder,that we daily exhort you to “take heed to yourselves and your doctrine;" and that we cease not to entreat you, and to pray for you that you give all diligence to approve your selves to God and his Church able and faithful servants? Independently of all official obligation, did we not feel and act thus, we should manifest an insensibility to the interests of the Church, as well as to your true welfare, equally inexcusable and degrading.

It is in consequence of this deep solicitude for your improvement in every kind of ministerial furniture, that we not only endeavour to conduct the regular course of your instruction in such a manner as we think best adapted to promote the great end of all your studies; but that we also seize the opportunity which the general Lecture, introductory to each session affords us, of calling your attention to a series of subjects, which do not fall within the ordinary course of our instruction.

A subject of this nature will engage our attention on the present occasion: namely, the importance of Creeds and Confessions for maintaining the unity and purity of the visible Church.

This is a subject, which, though it properly belongs to the department of Church Government, has always been, for want of time, omitted in the Lectures usually delivered on that division of our studies. And I am induced now to call your attention to it, because, as I said, it properly belongs to the department committed to me; because it is in itself a subject highly interesting and important; because it has been for a number of years past, and still is, the object of much severe animadversion, on the part of latitudinarians and heretics; and because, though abundantly justified by reason, Scripture, and universal experience,the spontaneous feelings of many, especially under the free government which it is our happiness to enjoy, rise up in arms against what they deem, and are sometimes pleased to call, the excessive “rigour” and even “tyranny” of exacting subscription to Articles of Faith.

It is my design, first, to offer some remarks on the utility and importance of written Creeds; and secondly, to obviate some of the more common and plausible objections which have been urged against them by their adversaries.

## I. 

By a Creed, or Confession of Faith, I mean, an exhibition, in human language, of those great doctrines which are believed by the framers of it to be taught in the Holy Scriptures; and which are drawn out in regular order, for the purpose of ascertaining how far those who wish to unite in church fellowship are really agreed in the fundamental principles of Christianity. Creeds and Confessions do not claim to be in themselves laws of Christ's house, or legislative enactments, by which any set of opinions are constituted truths, and which require, on that account, to be received as truths among the members of his family. They only profess to be summaries, extracted from the Scriptures, of a few of those great Gospel doctrines, which are taught by Christ himself; and which those who make the summary in each particular case, concur in deeming important, and agree to make the test of their religious union. They have no idea that, in forming this summary, they make anything truth, that was not truth before; or that they thereby contract an obligation to believe, what they were not bound by the authority of Christ to believe before. But they simply consider it as a list of the leading truths which the Bible teaches, which, of course, all men ought to believe, because the Bible does teach them; and which a certain portion of the visible church catholic agree in considering as a formula by means of which they may know and understand one another.

Now, I affirm, that the adoption of such a Creed is not only lawful and expedient, but also indispensably necessary to the harmony and purity of the visible Church. For the establishment of this position, let me request your attention to the following considerations.

### 1. Without a Creed explicitly adopted, it is not easy to see how the ministers and members of any particular church, and more especially a large denomination of Christians, can maintain unity among themselves.

If every Christian were a mere insulated individual, who inquired, felt, and acted for himself alone, no creed of human formation would be necessary for his advancement in knowledge, comfort, or holiness. With the Bible in his closet, and with his eyes opened to see the “wondrous things” which it contains, he would have all that was needful for his edification. But the case is far otherwise. The church is a *society*; a society which, however extended, is “one body in Christ," and all who compose it, “members one of another.” Nor is this society merely required to be one in name, or to recognize a mere theoretical union; but also carefully to maintain “the unity of the Spirit in the bond of peace.” They are exhorted to “stand fast in one spirit with one mind." They are commanded all to “speak the same thing," and to be “of one accord, of one mind.” And this “unity of spirit”, is as essential to the comfort and edification of those who are joined together in church fellowship, as it is to a compliance with the command of their Master. “How can any walk together unless they be agreed?” Can a body of worshippers, composed of Calvinists, Arminians, Pelagians, Arians, and Socinians, all pray, and preach, and commune together profitably and comfortably, each retaining the sentiments, feelings,and language appropriate to his denomination? This would indeed make the house ofGod a miserable Babel. What! can those who believe the Lord Jesus Christ to be God, equal with the Father, and worship him accordingly; and those who consider all such worship as abominable idolatry:–Those who cordially renounce all dependence on their own works or merit for justification before God, relying entirely on his rich grace, “through the redemption that is in Christ Jesus;" and those who pronounce all such reliance fanatical, and man's own righteousness the sole ground of hope: Can persons who cherish these irreconcilably opposite sentiments and feelings on the most important of all subjects, unite with edification in the same prayers, listen from Sabbath to Sabbath to the same instructions, and sit together in comfort at the same sacramental table? As well might Jews and Christians worship together in the same temple. They must either be perfectly indifferent to the great subjects on which they are thus divided, or all their intercourse must be productive of jarring and distress. Such a discordant assembly might *talk* about church fellowship; but that they should really *enjoy* that fellowship which the Bible describes as so precious, and which the pious so much delight to cultivate, is impossible; just as impossible as “that righteousness should have fellowship with unrighteousness,” or “light hold communion with darkness, or Christ maintain concord with Belial."

Holding these things to be self-evident, how, I ask, is any church to guard itself from that baleful discord, that perpetual strife of feeling, if not of words and conduct, which must ensue, when it is made up of such heterogeneous materials? Nay, how is a church to avoid the guilt of harbouring in its bosom, and of countenancing by its fellowship, the worst heresies that ever disgraced the Christian name? It is not enough for attaining this object, that all who are admitted profess to agree in receiving the Bible; for many who call themselves Christians, and profess to take the Bible for their guide, hold opinions, and speak a language as foreign, nay, as opposite, to the opinions and language of many others, who equally claim to be Christians, and equally profess to receive the Bible, as the east is to the west. Of those who agree in this general profession, the greater part acknowledge as of divine authority the whole sacred canon, as we receive it; while others would throw out whole chapters,and some a number of entire books from the volume of God's revealed will. The orthodox maintain the plenary inspiration of the Scriptures; while some who insist that they are Christians, deny their inspiration altogether. In short, there are multitudes who, professing to believe the Bible, and to take it for their guide,reject every fundamental doctrine which it contains. So it was in the beginning as well as now. An inspired Apostle declares, that some in his day, who not only professed to believe the Scriptures, but even to “preach Christ,” did really preach “another Gospel,” the teachers of which he charges those to whom he wrote to hold “accursed;" and he assures them that there are some “heresies” so deep and radical that they are to be accounted “damnable.” Surely those who maintain the true Gospel, cannot “walk together" in "church fellowship" with those who are “accursed” for preaching “another Gospel,” and who espouse “damnable heresies," the advocates of which the disciples of Christ are not permitted even to “receive into their houses, or to “bid God speed!” How, then, I ask again, are the members of a Church, to take care that they be, according to the divine command, “of one mind," and “of one way?” They may require all who enter their communion to profess a belief in the Bible; nay, they may require this profession to be repeated every day, and yet may be corrupted and divided by every form of the grossest error. Such a profession, it is manifest, ascertains no agreement; is a bond of no real union; a pledge of no spiritual fellowship. It leaves every thing within the range of nominal Christianity, as perfectly undefined, and as much exposed to total discord as before.

But perhaps it will be proposed as a more efficient remedy, that there be a private understanding, vigilantly acted upon, that no ministers or members be admitted, but those who are known, by private conversation with them, substantially to agree with the original body, with regard both to doctrine and order. In this way, some allege, discord may be banished, and a church kept pure and peaceful, without an odious array of Creeds and Confessions. To this proposal, I answer, in the *first* place, it is, to all intents and purposes, exhibiting a Creed, and requiring subscription to it, while the contrary is insinuated and professed. It is making use of a religious test, in the most rigorous manner, without having the honesty or the manliness to avow it. For what matter is it, as to the real spirit of the proceeding, whether the Creed be reduced to writing, or be registered only in the minds of the church members, and applied by them as a body, if it equally exclude applicants who are not approved! But to this proposed remedy, I answer, in the *second* place, the question, what is soundness in the faith? however explicitly agreed upon by the members of the church among themselves, cannot be safely left to the understanding and recollection of each individual belonging to the body in question. As well might the civil constitution of a State, instead of being committed to writing, be left to the vague and ever varying impressions of the individual citizens who live under it. In such a constitution, every one sees there could be neither certainty nor stability. Scarcely any two retailers of its articles would perfectly agree; and the same persons would expound it differently at different times, as their interests or their passions might happen to bear sway. Quite as unreasonable and unsafe, to say the least, would it be to leave the instrument of a church's fellowship on a similar footing. Such a nuncupative creed, when most needed as a means of quieting disturbances, or of excluding corruption, would be rendered doubtful, and, of course, useless, by having its most important provisions called in question on every side. A case in which, if it were made operative at all, it would be far more likely to be perverted into an instrument of popular oppression,than to be employed as a means of sober and wholesome government.

The inference then plainly is, that no church can hope to maintain a homogeneous character;— no church can be secure either of purity or peace, for a single year; nay, no church can effectually guard against the highest degrees of corruption and strife, without some test of truth, explicitly agreed upon, and adopted by her, in her ecclesiastical capacity; something recorded; something publicly known; something capable of being referred to when most needed; which not merely this or that private member supposes to have been received; but to which the church as such has agreed to adhere, as a bond of union. In other words, a church, in order to maintain “the unity of the Spirit in the bond of peace and love," must have a Creed - a written Creed - to which she has formally given her assent, and to a conformity to which her ministrations are pledged. As long as such a test is faithfully applied, she cannot fail of being in some good degree united and harmonious; and when nothing of the kind is employed, I see not how she can be expected, without a miracle, to escape all the evils of discord and corruption.

### 2. The necessity and importance of Creeds and Confessions appear from the consideration, that one great design of establishing a Church in our world was, that she might be in all ages, a depository, a guardian, and a witness of the truth.

Christians, collectively as well as individually, are represented in Scripture as witnesses for God. They are commanded to maintain his truth, and to “hold forth the word of life,” in all its purity and lustre before a perverse generation, that others may be enlight ened and converted. They are exhorted to “buy thetruth,and nottosellit;"_ to“con tend earnestly for the faith once delivered to the saints;" — to “hold fast the form of sound words which they have received;"— and to “strivetogetherforthe faithoftheGospel." These,and many other commands,of similar import, plainly make it the duty of every Christian church to detect and expose prevail
ing heresies; to exclude all such as embrace
radical heresy from their communion ; and to
6liftup a standard” fortruth,whenever the enemy comes in like a flood."
But does not all this imply taking effectual measures to distinguish between truth and error ? Does not all this necessarily infer the duty of drawing,and publicly manifesting, a line between those who,while they profess,in general, to believe the Bible, really deny all
itsessential doctrines;and thosewho simply and humbly receive "the truth as it is in
 2*

 Jesus?” But how is this distinction to be made,seeing those who embrace the essential doctrines of the Gospel, equally profess to receive the Bible? It can only be done by carefully ascertaining and explicitly declaring how the church herself,and how those whom she suspects of being in error,understand and interpret the Bible; that is, by extracting
certain articles of faith from the Scriptures, according to her understanding of them,and
comparing these articles with the professed
belief of those w h o m she supposes to be here
tics. A n d what is this but extracting from
the Scriptures a Confession of Faith- a Creed,
and applying it as a test of sound principles ? It does really appear to m e that those orthodox
brethren,who admit that the church is bound to raise her voice against error,and to “ con tend earnestly" for the truth; and yet de nounce Creeds and Confessions, are, in the highest degree inconsistent with themselves.
They acknowledge the obligation and im
portance of a great duty ; and yet reject the only means by which it can be performed. Quite as unreasonable,Iam constrained tosay, as the task masters of Egypt," they require
 18
UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 19
work to be done,without allowing the mate
rialsnecessarytoitsaccomplishment. Before
the church, as such,can detect heretics, and cast them out from her bosom : before she can
raise her voice, in “ a day of rebuke and of blasphemy,” against prevailing errors, her
governors and members must be agreed what istruth;and,unless they would give them selves up,in their officialjudgments,to allthe caprice and feverish effervescence of occasional feeling,they must have some accredited,per manent document,exhibiting what they have agreed to consider as truth. There is really no feasible alternative. They must either have such “ a form of sound words," which they have voluntarily adopted, and pledged themselves to one another to “ hold fast;" or
they can have no security that any two or
more successive decisions concerning sound ness in the faith will be alike. In other
words,they cannot attain,in any thing like a
steady,uniform,consistentmanner,oneofthe great purposes for which the visible church was established.
It surely will not be said,by any conside rate person, that the church, or any of her
 
 individual members, can sufficiently fulfil the
duty in question, by simply proclaiming from time to time, in the midst of surrounding error, her adherence and her attachment to
the Bible. Every one must see that this would be,in fact, doing nothing as “ witnesses of the truth ;" because it would be doing nothing peculiar; nothing distinguishing; n o thing which every heretic in Christendom is not ready to do,or rather is not daily doing, as loudly,and as frequently as the most ortho dox church. The very idea of “ bearing
testimony to the truth,” and of separating
from those who are so corrupt that Christian communion cannot be maintained with them,
necessarily implies some public discriminating act, in which the church agrees upon, and
expresses her belief in, the great doctrines of
Christianity, in contradistinction from those who believe erroneously. Now to suppose
that any thing of this kind can be accom plished, by making a profession, the very same,in every respect, with that which the
worst heretics m a k e , is too palpably absurd to satisfy any sober inquirer.
Ofwhat value,letme ask,had theWalden
 20 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 21
3. TheadoptionandpublicationofaCreed, is a tribute to truth and candour,which every
 ses and Albigenses been, as witnesses of the
truth - as lights in the world,amidst the dark
ness of surrounding corruption ;-especially of
what value had they been to the church in
succeeding times,and to us at the present day, if they had not formed, and transmitted to
posterity those celebrated Confessions of Faith , as precious as they are memorable,which we
read in their history, and which stand as so many monumental testimonies to the true
“Gospel of the grace of God ?” Without these, how should we ever have known in
what manner they interpreted the Bible; or
wherein they differed from the grossest here
tics,who lived at the same time,and professed
to receive the same Bible ? Without these,
how should we ever have seen so clearly and
satisfactorily as we do, that they maintained the truth and the order of Christ's house,
amidst all the wasting desolations of the “ m a n of sin;" and thus fulfilled his promise, that
thereshall always be “ aseed to servehim, who shall be accounted to the Lord for a
generation ?”

 Christian church owes to the other churches, and to the world around her.
 22
UTILITY AND IMPORTANCE
Every wise man will wish to be united in
religious duty and privilege,with those who
most nearly agree with himself in their views
ofdoctrineandorder;withthoseinintercourse
with whom he can be most happy,and best
edified. Ofcourse,hewillbedesirous,before
he joins any church,to know something of its
faith, government, and general character. I
will suppose a pious and ingenuous individual
about to form his religious connections for life. H e looks round on the churches to which he
has most access, and is desirous of deciding with which of them he can be most comfort
able. I will suppose that,in this survey,he turns his eyes towards the truly scriptural and
primitive church to which it is our happiness to belong. He is anxious to know the doc
trine as well as the order which he may expect tofindinconnectionwithourbody. Howis he to know this? Certainly not by going
from church to church throughout our whole bounds,and learning the creed of every indi vidualministerfromhisownlips. Thiswould
be physically impossible,without bestowing on

 OF CREEDS AND CONFESSIONS. 23
the task a degree of time and toil, which
scarcely any man could afford. He could not
actually hear for himself the doctrines taught
in a twentieth part of our pulpits. A n d if he c o u l d , h e w o u l d still b e u n a b l e t o d e c i d e , f r o m
thissource alone,how farwhat heheard might
be regarded as the uniform and universal, and
especially as the permanent character of the
church ; and not rather as an accidental exhibi
tion. But when such an inquirer finds that
we haveapublished creed,declaringhow we
understand the Scriptures,and explicitly stating
in detail the great truths which w e have agreed
to unite in maintaining; he can ascertain in a
few hours,and withoutleavinghisown dwell
ing,what we profess to believe and to practise,
and how far he may hope to be at home in our communion. And whileheisenabledthusto
understand the system to which we profess to adhere, he enables us to understand his views, by ascertaining how far they accord with our
published creed.
Further,what is thus due to ingenuous indi viduals,whowishtoknow therealcharacter of our church, is also due to neighbouring churches,who may have no lessdesiretoascer
 
 tain the principles which we embrace. It is delightful for ecclesiastical communities,who
approach near to each other in faith and order, to manifest their affection for one another,by
cherishingsomedegreeofChristianintercourse.
 24 UTILITY AND IMPORTANCE
But what church,which valued the preser
vationofitsown purityand peace,would ven
ture on such intercourse with a body which
had no defined system, either of doctrine or
government, to which it stood pledged ; and which might, therefore, prove a source of pol
lution and disorder to every other church with which it had the smallest interchange of ser vices? Oneoftheministersofsuchadenomi nation,when invited intothe pulpitofanor
thodox brother,might give entire satisfaction; while the very next to whom a similar mark ofChristianaffectionandconfidencewasshown, might preach the most corrupt heresy. Creeds
and Confessions, then, so far from having a tendency to “ alienate ” and “ embitter ” those Christian denominations which think nearly alike,and ought to maintain fraternal inter
course,really tend to make them acquainted with each other; to lay a foundation for regu
lar and cordial intercourse; to beget mutual
.

 OF CREEDS AND CONFESSIONS. 25
I scruple not, therefore, to affirm , that, as every individual minister owes to all around
him a frank avowal of his Christian faith,
when any desire to know it; so every church owes it to her sister churches,to be equally
frank and explicit in publicly declaring her principles. She,nodoubt,believesthoseprin ciples to be purely scriptural. In publicly avowing them, therefore, she performs the double duty of bearing testimony to the truth, and of endeavouring to draw from less pure denominations,andfromthesurroundingworld, new support to what she conscientiously be lieves to be more correct sentiments than theirs. Shemaybeerroneousinthisestimate; but still she does what she can,and what she unfeignedly believes to be right; and what, of course,as long as this conviction continues,she isbound toperform. And I have no hesita tion in further maintaining, that, in all ages, those Christian churches which have been most honourably distinguished for their piety, their zeal,and their adherence to the simplicity of the gospel,have been, not only most re
 confidence; and thus to promote the harmony of the church of G o d .
3

 markable for their care in forming, but also for their frankness in avowing, their doctrinal creed; and their disposition to let all around
them distinctly understand what they professed to regard as the fundamental doctrines of our holy religion.
It is the general principle of the enemies of Creeds, that all who profess to believe the Bible,ought,withoutfurtherinquiry,tounite;
to maintain ecclesiastical communion ; and to
livetogetherinpeace. Butisitnotmanifest,
that the only way in which those who essen
tially differ from each other concerning the fundamental doctrines of the gospel, can live
together in perfectly harmonious ecclesiastical fellowship,isby becoming indifferenttotruth; in other words, by becoming persuaded that modes of faith are of little or no practical i m portance to the Church,and are,therefore,not
worth contending for; that clear and discrimi nating views of Christian doctrine are wholly
 26 UTILITY AND IMPORTANCE
4. Another argument in favour of Creeds publicly adopted and maintained,is that they are friendly to the study of Christian doctrine,
and,of course,to the prevalence of Christian knowledge.

 OF CREEDS AND CONFESSIONS. 27
 unnecessary,and of littleuse in the formation ofChristian character? But in proportion as
professing Christians are indifferent to truth, will they not be apt to neglect the study of it? And ifthestudyofitbegenerallyneglected, will not gross and deplorable ignorance of it eventuallyandgenerallyprevail? Thefactis,
when men love gospel truth well enough to study it with care,they will soon learn to esti
mateitsvalue;theywillsoon bedisposed to
“ contend for it,” against itsenemies,who are
numerousineveryage;andthiswillinevitably
lead them to adopt and defend that “ form of
sound words ” which they think they find in
the sacred Scriptures. On the other hand,let
any man imbibe the notion that Creeds and
Confessions are unscriptural, and of course u n
lawful, and he will naturally and speedily pass
totheconclusion,thatallcontending fordoc trines is useless,and even criminal. From
this the transition is easy to the abandonment of the study of doctrine,or,at least,the zealous
anddiligentstudyofit. Thusitis,thatlaying aside all Creeds,naturally tends to make pro fessing Christians indifferent to the study of Christian truth ; comparatively uninterested in

 I would by no means, indeed,be understood to assert,that no heretics have ever been zea lous in publishing and defending their corrupt opinions. The pages of ecclesiastical history abundantly show , that m a n y of the advocates of error,both in ancient and modern times, have contended not only pertinaciously, but even fiercely,for their peculiar doctrines. But m y position is, that the enemies of all Creeds and Confessions usually assume a principle, which,if carried out to its legitimate conse quences, would discourage all zeal in m a i n
taining the peculiar doctrines of the gospel; that if all zeal in maintaining peculiar doc trines were laid aside, all ardour and diligence
in studying them would be likely to be laid aside also; and that,if this were the case,a
state of things more unfriendly to the growth and prevalenceof Christian knowledge could scarcely be imagined. Look at the loose, vague,undecisive character of the preaching heard in nine-tenths of the Unitarian, and
other latitudinarian pulpits in the United
 28 UTILITY AND IMPORTANCE
the attainment of religious knowledge ; and, finally,regardless, and,of course, ignorant of
the faith once delivered to the saints."

 OF CREEDS AND CONFESSIONS. 29
 States, and, as I suppose, throughout Chris tendom. If the occupants of those pulpits h a d it f o r t h e i r d i s t i n c t a n d m a i n o b j e c t t o r e n der their hearers indifferent about understand
ing,and,ofcourse,indifferentaboutstudying, the fundamental doctrines of the gospel,they
could scarcely adopt a plan more directly cal
culated to attain their end, than that which
they actually pursue. Their incessant cry is,
“matters of opinion are between God and a man's own conscience. No one else has a
righttomeddlewiththem.” Hence,inpur
suance ofthis maxim,theydo,indeed,take
care to meddle very littlewith the distinguish
ing doctrines of the gospel. W e conjecture what their doctrinal opinions are,in general,
not so much from what they say,asfrom what theydonotsay. And thetruthis,thatif
this character of preaching was to become universal,alldiscriminating views of gospel truth would,in thirty years,be banished from the church.
3*
If the friends of orthodoxy and piety,then, really desire to cherish and maintain a love for the discriminating study of Christian d o c trine;a taste for religious knowledge; a spirit

 of zeal for the truth, in opposition to that miserable indifference to articlesof faith,which is so replete with mischief to every Christian community in which it is found; then let them be careful to present,and diligently keep before the eyes of one another,and the eye of the public, that “ good confession "
which they are commanded to “ profess before many witnesses.”
 30 UTILITY AND IMPORTANCE
If they fail to do this;if,
under the guise of adherence to that great P r o testantmaxim,thattheBibleistheonlyinfal lible rule of faith and manners,— (a precious all-important truth; which, properly under stood, cannot be too often repeated)—they speakandactasifallwho professtoreceive the Bible were standing upon equally solid and safe ground; if,in a word,they consider itasunnecessary,and even criminal,toselect from the mass of Scriptural truth,and to de fend, as such, the fundamental doctrines of the gospel;—then , nothing short of miracle can prevent them from sinking into that coldness and sloth with respect to the study of doc
trine,and finally into that deplorable “ lack of
knowledge” by which millions are constantly “ destroyed .”

 OF CREEDS AND CONFESSIONS. 31
5. It is an argument of no small weight in favour of Creeds, that the experience of all ages has found them indispensably necessary.
Even in the days of the Apostles, when all
their inspiration and all their miraculous p o w ers, were insufficient to deter heretics from
spreading their poison ;- m e n , calling t h e m selves Christians, and professing to preach the
religion of Christ, perverted his truth, and brought another gospel,” which He had not t a u g h t. I n t h i s e x i g e n c y , h o w d i d t h e c h u r c h e s proceed? An inspiredapostledirectedthem not to be contented with a general profession of belief in the religion of Christ on the part of thosewho came tothem asChristian teach ers; but to examine and try them, and to ascertain whether their teaching were agreeable to the f o r m of sound words” which they had
been taught by him : and he adds with awful solemnity- " Ifany man bring any other gos pel unto you than that ye have received, let him be accursed.” Here was, in effect, an
instance, and that by Divine warrant, of e m
ploying a Creed as a test of orthodoxy : that is,men making a general profession of Chris
tianity, are expressly directed by an inspired
 
 In the second century, in the writings of Irenæus;and,in the third,in the writings of Tertullian,Origen,Cyprian,Gregory Thau maturgus, and Lucian,the martyr,we find a number of Creeds and Confessions, more for mally drawn out,more minute,and more ex tensive than those of earlier date. They were intended to bear testimony against the various forms of error which had arisen;and plainly show that,as the arts and corruptions of here tics increased,the orthodox church found more attention to the adoption and maintenance of these formularies indispensably necessary .
In the fourth century,when the church was
 32 UTILITY AND IMPORTANCE
apostle, to be brought to the test,in what sense they understood that gospel, of which, in
general terms, they declared their reception ;
and how they explained its leading doctrines. It would seem ,indeed,that the Confession of
Faith then required was very short and sim
ple. This,thepeculiarcircumstancesofthe
times,and the no less peculiar administration
of the Church, rendered entirely sufficient.
Still, whether the Confession were long or short; whether it consisted of three articles or
of thirty,the principlewas the same.

 OF CREEDS AND CONFESSIONS. 33
stillmoreagitatedbytheprevalenceofheresy, there was a still louder demand for accredited
tests,by which the heretics were to be tried and detected. Of this demand there never
was a more striking instance than in the C o u n
cil of Nice, when the heresy of Arius was under the consideration of that far-famed as
sembly. When the Council entered on the examination of the subject,it was found ex
tremelydifficulttoobtainfromAriusanysatis
factory explanation of his views. H e was not only as ready as the most orthodox divine
present, to profess that he believed the Bible ; but he also declared himself willing to adopt,
as his o w n , all the language of the Scriptures, in detail, concerning the person and character oftheblessedRedeemer.Butwhen themem bers of the Council wished to ascertain in what
sense he understood this language,he disco vered a disposition to evade and equivocate, and actually, for a considerable time, baffled
the attempts of the most ingenious of the ortho dox to specify his errors,and to bring them to light. He declaredthathewas perfectlywil
ling to employ the popular language on the subject in controversy ; and wished to have it
 -

 34 UTILITY AND IMPORTANCE
believed that he differed very little from the body of the church. Accordingly the orthodox went over the various titles of Christ plainly expressive of Divinity, such as “God”
“t h e t r u e G o d ” — t h e “ e x p r e s s i m a g e o f G o d ,” & c.— to every one of which Arius and his followers most readily subscribed;—claiming a right,however, to put their own construc tion on the scriptural titles in question. After employing much time and ingenuity in vain, in endeavouring to drag this artful chief from his lurking places,and to obtain from him an explanation of his views, the Council found it would be impossible to accomplish their object as long as they permitted him to in trench himself behind a mere general profes
sion of belief in the Bible. They therefore, did,what common sense,as well as the word of God, had taught the church to do in all preceding times,and what alone can enable hertodetecttheartfuladvocateoferror.They expressed,in their own language,what they supposed to be the doctrine of Scripture c o n cerning the Divinity of the Saviour ; in other words, they drew up a Confession of Faith on this subject,which they called upon Arius and
 
 OF CREEDS AND CONFESSIONS. 35
The same course was taken by all the pious witnesses of the truth in the dark ages,when,
amidst the surrounding corruption and deso
lation, they found themselves called upon to bear“witnesstothetruth.” Theyallpro
fessed their belief in the Bible,and their love to it; they constantly appealed to it, as the only infallible rule of faith and practice; and they studied it with incomparably more vene ration and diligence than any of the errorists around them. This all history plainly evin
But at the same time,they saw the futi lity of doing nothing more than proclaim in general,their adherence to the sacred volume. This would have been no distinction,and,of course, no testimony at all. It would have been nothing more than the bitterest enemies
of the truth were proclaiming busily,and even clamorously,everyday. They,therefore,did
what the friends of orthodoxy had been in the
 his disciples to subscribe. This the heretics
refused : and were thus virtually brought to
the acknowledgment that they did not under stand the Scriptures as the rest of the Council understood them, and, of course, that the charge against them was correct.
ces.

 36 UTILITY AND IMPORTANCE
What,now,is the inference, from all this experienceoftheChurch ofGod,souniversal and so uniform ? It cannot be misunderstood.
Itspeaksvolumes. Whenthefriendsoftruth inallagesandsituations,eventhosewho were
habit of doing from the earliest ages. They framed creeds,from time to time,as the exi
genciesofthe Church demanded,by means of which they were enabled to bear their testi mony for God ; to vindicate his truth; and to transmit the memorials of their fidelity to dis tantgenerations. Andfinally,attheglorious Reformation from Popery,by which the great Head ofthe Church may be saidagain tohave
“ set his people free," and the memory of
which shall never die; in drawing the line between “the precious and the vile,” the friends of truth followed the same course.
They,with one accord, formed their Creeds
and Confessions, which served, at once,as a
plea for the truth,and a barrier against heresy.
And itisnot,perhaps, too much to say,that the volume which contains the collection of
these Creeds,isone of the most precious and
imperishablemonuments ofthe piety,wisdom, and zeal of the sixteenth century .
 
 OF CREEDS AND CONFESSIONS. 37
A further argument in favour of Creeds and Confessions, may be drawn from the remarkable fact, that their most zealous o p posers have generally been latitudinarians and
heretics.
I do not affirm that the use of Creeds has
never been opposed by individuals substantial ly orthodox, and even by orthodox churches: for it is believed that a few rare cases of this anomaly have occurred, under the influence of strong prejudice, or very peculiar circum stances. Yet, so far as I can recollect, we have no example of it among the ancients.
 most tenacious of the rights of private judg ment, and most happy in the enjoyment of
Christian liberty, have invariably found it necessary to resort to the adoption of Creeds,
in order to ascertain for themselves, as a social body,and tocommunicatetoothers,fortheir benefit,their sense of the holy scriptures;
we arenaturallyledtoconclude,notonlythat theresortisneitherso unreasonable"norso
“baneful”asmanywould persuadeustobe lieve; but that there is really no other practi cable method of maintaining unity and purity in the Church of Christ.
4

 Such cases are the growth of very modern times. Nor,on theotherhand,isitmy pur pose to deny that heretics have sometimes
been extremely zealous in forming and m a i n taining the most corrupt Creeds. For of this the early history of the Church abounds with examples, and its later periods have not been wholly without them . But what I venture to assert is, that, as a general fact, the most ardent and noisy opponents of Creeds have been those who held corrupt opinions; that none,calling themselves.Christians,have been so bitter in reviling them , in modern times, as the friends of Unitarianism , and those who were leaning toward that awful gulf; and that the most consistent and zealous advocates of truth have been, every where, and at all
times, distinguished by their friendship to such formularies. Nor has this been by any
means a fortuitous occurrence ; but precisely what might have been calculated, on princi ple,aslikelytoberealized. Itisan invaria
ble characteristic of the orthodox that they lay great stress on the knowledge and recep tion of truth ; that they consider it as neces sary to holiness; that they deem an essential
 38 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 39
part of fidelity to their Master in heaven,to
consist in contending for it, and maintaining itinoppositiontoalltheforms oferror.
 the contrary, it is almost as invariable a cha racteristic of modern heretics,and more espe
cially of those who fall under the general denomination of Unitarians, that they profess
lightly to esteem modes of faith; that they manifestamarked indifferencetotruth;that
they,for the most part, maintain, inso many words,the innocenceoferror;and hence very naturally reprobate, and even vilify, all faith ful attempts to oppose heresy, and to separate
heretics from the Church. From those,then, who have eitherfardeparted,oratleastbegun to depart, from “ the faith once delivered to
the saints,” almost exclusively, do we hear of the “ oppression," and the “mischief” of CreedsandConfessions.'And isitanymar vel that those w h o maintain the innocence of
error, should be unwilling to raise fences for
keepingitoutoftheChurch? Isitanymar vel that the Arian,the Socinian,the Pelagian,
and such as are verging toward those fatal
dislike all the formularies, which tend to make
errors, should exceedingly evangelical
On

 visible the line of distinction between the friends and the enemies of the Redeemer? No ;“men ,"as has been often well observed, " men are seldom opposed to Creeds, until Creedshavebecomeopposedtothem.” That they should dislike and oppose them , in these
circumstances,isjustasnaturalas thatacul prit arraigned before a civil tribunal, should equally dislike the law, its officer, and its sanction.
 40 UTILITY AND IMPORTANCE
Accordingly, if we look a little into the interior of Church history, especially within thelastcentury,we shall find these remarks
often and strikingly exemplified. W e shall find, with few exceptions, that whenever a group of men began to slide, with respect to orthodoxy,theygenerallyattemptedtobreak, if not to conceal, their fall, by declaiming against Creeds and Confessions. They have
seldom failed,indeed, to protest in the begin ning,that they had no objections to the doc trines themselves of the Confession which
they had subscribed, but to the principle of subscribing Confessions at all. Soon, h o w ever, was the melancholy fact gradually un folded, that disaffection to the doctrines which

 OF CREEDS AND CONFESSIONS. 41
they once appeared to love,had more influence in directing their course,than even they t h e m selves imagined,and that they were receding further and further from the g o o d way " in
which they formerly seemed to rejoice. Truly that cause is of a most suspicious character to which latitudinarians and heretics, at least in modern times, almost as a matter of course, yield their support; and which they defend
with a zeal, in general, strictly proportioned to their hatred of orthodoxy !
 7. The only further argument in support of
Creeds on which I shall dwell,is,that their
most zealous opposers do themselves virtually
employ them in all ecclesiastical proceedings. The favourite maxim,withtheopposersof
Creeds,that all who acknowledge the Bible, ought,without hesitation,to be received,not only to Christian, but also to ministerial c o m munion,isinvariablyabandoned by thosewho urge it, the moment a case turns up which reallybringsittothetest. Didanyoneever hear of a Unitarian congregation engaging as
theirpastorapreacherofCalvinism,knowing him to be such ? But why not,on the princi
ple adopted, or at least professed, by Unita
4*

 rians? The Calvinist surely comes with his Bible in his hand,and professes to believe it as cordially as they. W h y is not that enough ?
Yet we know that,in fact,itisnot enough for theseadvocatesofunboundedliberality. Be fore they will consent to receive him as their spiritual guide, they must be explicitly in formed,how he interprets the Bible; in other words,what ishisparticularCreed;whether itissubstantiallythe same with theirown or not : and if they are not satisfied that this is
the case,all other professions and protestations will be in vain. He will be inexorably re
jected. Here,then,we have,inallitsextent, the principle of demanding subscription to a Creed ; and a principle carried out into prac
tice as rigorously as ever it was by the most high -toned advocate of orthodoxy .
We havebeforeseen,thatthefriendsof truth, in all ages, have found, in their sad
experience, that a general profession of belief in the Bible,was altogether insufficient,either
as a bond of union, or as a fence against the inroads of error. A n d here w e find the
warmest advocates of a contrary doctrine,and with a contrary language in their mouths,
 42 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 43
when they come to act,pursuing precisely the same course with the friends of Creeds,with
only this difference,that the Creed which they apply as a test,instead of being a written and tangible document,is hidden in the bosoms of
those who expound and employ it, and, of
course,may be applied in the most capricious
aswellastyrannical manner,without appeal;
and further, that, while they really act upon
this principle,they disavow it,and would per suade the world that they proceed upon an
entirely different plan.
Can there be a more conclusive fact than
this? The enemies of Creeds themselves can
not get along a day without them. It is in
vain to say, that in their case no Creed is
imposed, but that all is voluntary, and left
entirely to the choice of the parties concerned. It will be seen hereafter that the same may be
with equal truth asserted, in all those cases of subscription to articles, for which I contend,
withoutanyexception. No lessvainisitto say,again,thatintheircasethearticlesinsisted on are few and simple, and by no means so
Jiable to exception as the long and detailed Creeds which some churches have adopted,
 
 It is the principle of subscription to Creeds which is now under consideration. If the
lawfulness and even the necessity of acting upon this principle can be established, our cause is gained. The extent to which we ought to go in multiplying articles, is a secon dary question, the answer to which must depend on the exigencies of the church framing the Creed . N o w the adversaries of
Creeds,while they totally reject the expedi ency,and even the lawfulness, of the general
principle,yet show that they cannot proceed a step without adopting it in practice. This
is enough . Their conduct is sounder than their reasoning And no wonder. Their
conduct is dictated by good sense and prac
tical experience, nay,imposed upon them by
the evident necessity of the case: while their
reasoning is a theory, derived, as I must
believe,from a source far less enlightened,and less safe.
Several other arguments might be urged in favour of written Creeds,did not the limits to
which I am confined in this Lecture, forbid m e further to enlarge.
 44
UTILITY AND IMPORTANCE
It were easy to show that Confessions of

 OF CREEDS AND CONFESSIONS. 45
Faith,judiciously drawn,and solemnly adopt ed by particular churches,are not only invalu able as bonds of union, and fences against error; but that they also serve an important purpose, as accredited manuals of Christian doctrine, well fitted for the instruction of those private members of churches,who have neither leisure nor habits of thinking suffi ciently close,to draw from the sacred writings themselvesaconsistentsystemoftruth. Itis of incalculable use to the individual w h o has
but little time for reading, and but little ac quaintance with books,to be furnished with a
clear and well arranged compend of doctrine, which he is authorized to regard, not as the
work of a single, enlightened, and pious di vine; but as drawn out and adopted by the collected wisdom of the Church to which he
belongs. There is often a satisfaction, to plain,unsophisticated mind,not to be descri
bed,in going over such a compend,article by article; examining the proofs adduced from the word of God in support of each; and “ searching the Scriptures daily to see w h e
ther the things which it teaches are so or not.”
 
 Itmightalso be furthershown,thatsound and scriptural Confessions of Faith, are of great value for transmitting to posterity knowledge of what is done by the Church , at particular times,in behalf of the truth. Every such Confession that is formed or adopted by the followers of Christ in one age,isa pre
cious legacy transmitted to their children,and toallthatmay come afterthem,inasucceed ing age, not only bearing their testimony in support of the true doctrine of Jesus Christ,
but also pouring more or less light on those doctrines, for the instruction of all to w h o m that testimony may come.
1. A n d the first which I shall mention is, that forming a Creed,and requiring subscrip tion to it as a religious test, is superseding the
Bible,and making a human composition in steadofitastandardoffaith. “TheBible,"
 46 UTILITY AND IMPORTANCE
But while we attend to the principal argu ments in favour of written Creeds, justice to
the subject requires that w e
II. Examine some of the principal objec
tions which have been made to Creeds by their adversaries.

 OF CREEDS AND CONFESSIONS. 47
saythosewho urge thisobjection,“istheonly infallible rule of faith and practice. It is so
complete, that it needs no human addition, and so easily understood , that it requires no
human explanation. W h y , then, should we desire any other ecclesiastical standard ? W h y subscribe ourselves,or call upon others to sub scribe, any other Creed than this plain, in spired, and perfect one ? Every time we do this w e offer a public indignity to the sacred volume,as we virtually declare,either that it is not infallible, or not sufficient."
This objection is the most specious one in thewhole eatalogue. And althoughitisbe lieved that a sufficientanswer has been fur nished by some principles already laid down ; yet the confidence with which it is every day repeated, renders a formal attention to it e x pedient; more especially as it bears, at first view,so much the appearance of peculiar vene ration for the Scriptures,that many are capti
vated by its plausible aspect,and consider it as decisive.
The whole argument which this objection presents, is founded on a false assumption.
No Protestant ever professed to regard his
 
 Creed,considered as a human composition,as of equal authority with the Scriptures, and far
lessofparamountauthority. Everyprinciple o f t h i s k i n d is , w i t h o n e v o i c e , d i s c l a i m e d , b y
all the Creeds, and defences of Creeds, that I
haveeverread. And whether,notwithstand
ing this, the constant repetition of the charge, ought to be considered as fair argument,or
gross calumny, the impartial will judge. A church Creed professes to be,as was before observed,merely an epitome,or summary ex hibitionofwhattheScripturesteach. Itpro fesses to be deduced from the Scriptures, and
to refer to the Scriptures for the whole of its authority. Of course,when any one subscribes it,he is so far from dishonouring the Bible, that he does public homage to it. -H e simply declares,by a solemn act,how he understands
the Bible; in other words, what doctrines he
considersitascontaining. Inshort,thelan
guage of an orthodox believer, in subscribing
his ecclesiastical Creed, is simply of the fol
lowing import :- “ While the Socinian pro fesses to believe the Bible, and to understand
it as teaching the mere humanity of Christ: while the Arian professes to receive the same
 48 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 49
Bible,and to find in it the Saviour represented asthemost exaltedofallcreatures,butstilla creature:- While the Pelagian and Semi-Pela gian m a k e a similar profession of their general belief in the Scriptures, and interpret them as teaching a doctrine, far more favourable to human nature,and far less honourable to the grace of G o d , than they appear to m e really to teach ;— I beg the privilege of declaring, for
myself,that,while I believe,with all m y heart, that the Bible is the word of God ,the only
perfect rule of faith and manners,and the only ultimate test in all controversies — it plainly
teaches, as I read and believe — the deplorable andtotaldepravityofhumannature— theessen tial divinity of the Saviour — aTrinity of per sons in the Godhead — justification by the i m puted righteousness of Christ — and regenera tion and sanctification by the Holy Spirit,as indispensable to prepare the soul for heaven. These I believe to be the radical truths which God hath revealed in his word;and while they are denied by some,and frittered away
or perverted by others,who profess to believe that blessed word,I am verily persuaded they
 5

 are the fundamental principles of the plan of salvation."
nouring the Scriptures,or setting up a stand a r d a b o v e t h e m , t h e r e is a n e n d o f all m e a n i n g either of words or actions.
B u t still it is a s k e d _ o W h e r e is t h e n e e d o f
any definitive declaration of what we under stand the Scriptures to teach? Are they not intelligible enough in themselves ? Can we make them plainer than their Author has done? Why holdacandletothesun? Why make an attempt to frame a more explicit test than He who gave the Bible has thought pro per to frame :- a n attempt, as vain as it is presumptuous?” To thisplea itissufficient
 50 UTILITY AND IMPORTANCE
Now,Iask,isthereinallthislanguage,any
thingdishonourabletotheBible? Anything that tends to supersede its authority ; or to
introduce a rule, or a tribunal of paramount authority? Is there not,on the contrary,in
the whole language and spirit of such a decla ration,an acknowledgment of God's word as of ultimate and supreme authority ; and an e x pression of belief in certain doctrines,simply and only because they are believed to be r e vealed in that word? Truly,if this be dis

 OF CREEDS AND CONFESSIONS. 51
to answer, that, although the Scriptures are undoubtedly simple and plain; so plain that
“ he who runs may read;" yet it is equally certain that thousands do,in fact,mistake and misinterpret them . This cannot possibly be denied;becausethousandsinterpretthem,and that on points confessedly fundamental, not only in different, but in directly opposite ways. Ofcourseallcannot be equallyright. Can it be wrong,then,for a pious and ortho dox man -or for a pious church,to exhibit, and endeavour to recommend to others,their modeofinterpretingthesacredvolume? As the world is acknowledged,on all hands,to be, in fact, full of mistake and error as to the true meaning of Holy Scriptures, can it be thought a superfluous task for those who have
more light,and more correct opinions,to hold them up to view,as a testimony to the truth, and as a guide to such as may be in error? Surely it cannot. Yet this is neither more nor less than precisely that formation and mainte nance of a scriptural Confession of Faith for which I am pleading.
Still,however,itmay be asked,what right has any man,or set of men to interpose their
 
 52 UTILITY AND IMPORTANCE
authority,and undertake to deal out the sense of Scripture for others? Is it not both impious
in itself,and an improper assumption over the minds of our fellow men ? I answer, this reasoning would prove too much, and there fore proves nothing. For, if admitted, it would prove that all preaching of the gospel
is presumptuous and criminal; because preach ing always consists in explaining and enfor cing Scripture,and that,for the most part,in the words of the preacher himself. Indeed, ifthe objection before us were valid,itwould
1 1
prove that all the pious writings of the most eminentdivines,inallages,whohave hadfor
their object to elucidate and apply the word of God,were profane and arrogant attempts to
mend his revelation,and make it better fitted than it istopromote its great design. Nay,
further; upon the principle of this objection, it not only follows, that no minister of the
gospel ought ever do more in the pulpit than simply to read or repeat the very words of Scripture; but it is equally evident, that he must read or repeat Scripture to his hearers, only in the languages in which they were giventotheChurch. For,ashasbeenoften
2
 
 OF CREEDS AND CONFESSIONS. 53
observed,itcannot be said,that the words of any translation of the Bible are the words
oftheHolySpirit. Theyareonlythewords which uninspired men have chosen,in which to express, as nearly as they were able, the
senseoftheoriginal. If,therefore,the objec tion before us be admitted,no man isat liberty
to teach the great truths of revelation in any other way than by literally repeating the H e brew text of the Old Testament, and the Greek of the N e w ,in the hearing of the peo ple. Soextremeistheabsurditytowhichan erroneous principle will not fail to lead those who are weak enough,or bold enough,to fol low it to its legitimate consequences !
But,after all,what language do factsspeak on this subject? Are those individuals or churches, who have been most distinguished for their attachment and adherence to creeds, more regardless of the Bible than other pro fessing Christians ? D o they appear to esteem the Bible less? Do they read it less? Do they appeal to it less frequently, as their grand and ultimate authority ? D o they quote it more rarely,or with less respect in their preaching ? Where they once refer to their
 very
5*

 54
UTILITY AND IMPORTANCE
Creeds or Catechisms,for either authority or
illustration, in the pulpit, do they not, noto riously, refer to the Bible a thousand times ?
D o they take less pains than others to impress the contents of the sacred volume on the
m i n d s o f t h e i r c h i l d r e n , a n d t o h o l d it f o r t h a s theunceasingobjectofstudytoall? Lookat the reformed churches of Scotland and H o l land, of France and Geneva, in their best state, when their Confessions of Faith were most venerated, and had most power; and then say, whether any churches, since the days of the apostles, ever discovered more reverence for the Scriptures,or treated them with more devout regard,as the only perfect
standard of faith and practice, than they ?
Nay,am I not warranted in making a similar 1 appeal with respect to those churches in our land,which have been most distinguished for
their attachment to creeds ? Are not their ministers,in general,quite as remarkable for very rarely quoting their own ecclesiastical formularies, for either proof or illustration, as they are for their constant and abundant q u o tations from Scripture for both purposes? Can the same incessant and devout recurrence
 
 OF CREEDS AND CONFESSIONS. 55
to the sacred oracles be ascribed with equal truth to the great body of the opposers of Creeds,in ancient or modern times ? I will not press this comparison into further detail; but have no apprehension that even the bitter estenemy of Creeds,who has a tolerable ac
quaintance with facts,and the smallest portion of candour,will venture to say that the result fairly deduced , is in favour of his cause .
2. Another objection frequently made to church Creeds is,that they interfere with the rights ofconscience,and naturally lead to op pression. “W h a t right," say those w h o urge
this objection, “ has any church, or body of churches,toimposeaCreedon me,ordictate tomewhatIshallbelieve? Toattemptsuch dictation is t y r a n n y ; to s u b m i t to it, is to s u r render the right of privatejudgment.”
 There would be some ground for this objec tion,ifaCreed were,inany case,imposed by the civil government, or by an established Church ; ifany were obliged to receive it, un
der heavy pains and disabilities,whether they approved it or not. But as such a case does
not,and,happily,cannot exist in our favoured country , the objection is surely as illegitimate

 56 UTILITY AND IMPORTANCE
 in reasoning, as it is false in fact. One is
tempted to suspect that those who urge such an objection among us,have found itmanufac tured to their hands, by persons living under civil governments and ecclesiastical establish ments of an oppressive character; and view ing it as a weapon which might be wielded with much popular effect,they have taken it into their service,and thenceforward refused to abandon it; though proved a thousand times to have no more application to any Creed or
church in the United States,than to the in habitants of another planet.
It will not, surely, be denied by any one,
that a body of Christians have a right, in every free country, to associate and walk to
gether upon such principles as they may choose to agree upon, not inconsistent with public order. They have a right to agree and declare how they understand the Scriptures; what articles found in Scripture they concur in considering as fundamental; and in what manner they will have their public preaching and polity conducted, for the edification of themselves and their children. They have no
right,indeed,to decide or tojudge for others,

 OF CREEDS AND CONFESSIONS. 57
nor can they compel any man to join them. But it is surely their privilege to judge for themselves; to agree upon the plan of their own association; to determine upon what
principles they will receive other members into their brotherhood ; and to form a set of rules which will exclude from their body those with whom they cannot walk in har mony. The questionis,notwhetherthey make in all cases,a wise and scriptural use of this right to follow the dictates of conscience, but whether they possess the right at all? They are, indeed, accountable for the use w h i c h t h e y m a k e o f it, a n d s o l e m n l y a c c o u n t able,to their Master in heaven; but to man they surely cannot, and ought not, to be c o m
pelled to give any account. It is their own
 eoncern. Their fellow -men have nothing to do with it,as long as they commit no offence
againstthepublicpeace.To decideotherwise, would indeed be an outrage on the right of private judgment. If the principles of civil
and religious liberty, generally prevalent in our happy country,be correct,demonstration itself cannot be more incontrovertible than
these positions.

 58 UTILITY AND IMPORTANCE
But ifa body of professing Christians have
a natural right thus to associate, to extract
their own Creed from the Scriptures,and to agree upon the principles by which others
m a y afterwards be admitted into their n u m ber;isitnotequallymanifest that theyhave the same right to refuse admittance to those with w h o m , they believe,they cannot be c o m fortably connected ?
 Let us suppose a church to be actually asso ciated upon the principle laid down ; its Creed and other articles adopted, and published for theinformationofallwho may wish tobe in formed; and itsmembers walking togetherin harmony and love. Suppose,while things are inthissituation,aperson comes to them,and
addresses them thus : “ I demand admittance
into your body,though I can neither believe
the doctrines which you profess to embrace,
nor consent to be governed by the rules
whichyouhaveagreedtoadopt." Whatan
swerwouldtheybeapttogivehim? They
would certainly reply : " Your demand is very unreasonable. Our union is a voluntary one,
for our mutual spiritual benefit. W e have not solicited you tojoin us; and you cannot pos

 OF CREEDS AND CONFESSIONS. 59
sibly have a right to force yourself into our
body. The whole world is before you. Go
where you please. W e cannot agree to receive
you , unless you are willing to walk with us
upon our own principles.” Such an answer
would undoubtedly be deemed a proper one
by every reasonable person. Suppose, h o w
ever,this applicant were stilltourge his de
mand ; to claim admission as a right; and,
upon being finally refused, to complain,that
the society had “persecuted” and “ injured”
him? Would any one think him possessed of
common sense? Nay,would not the society
inquestion,iftheycouldbe compelledto re
ceive such an applicant,instead of being op pressorsofothers,ceasetobefreethemselves?
The same principle would still more strong
ly apply,in case of a clergyman offering him
selftosuch a church,as a candidate for the
station ofpastor among them. Suppose,when
he appeared to make a tender of his services,
they were to present him with a copy of that
Creed,and ofthatform of government and of
worship which they had unanimously adopted, andtosay—“Thisiswhatwebelieve. We
pretend not to prescribe to others ; b u t so w e
 
 have learned Christ;' so we understand the Scriptures;and thus we wish ourselves, our
children,andallwholookuptousfor guid ance,to be instructed. Can you subscribe to these formularies? Are you willing to come
among us upon these principles, and,asour pastor, thus to break to us, and our little ones, what we deem the bread of life?'» Could
the candidate complain of such a demand ? Manyspeakasifthe church,inputtinghim to this test, undertook to “ judge for him .” But nothing can be more remote from the truth. They only undertake to judge for
themselves. If the candidate cannot, or will
not, accept of the test, he will be, of course ,
rejected. But, in this case, no judgment is
passed on his state toward God ; no ecclesias
tical censure,not even the smallest,isinflicted
uponhim. Thechurchonlyclaimarightto
be served in the ministerial office by a man
who isof the same religion with themselves. And is this an unreasonable demand ? Are
not the rights of conscience reciprocal? Or do they demand,that while a church shall be
prohibited from “ oppressing” an individual, an individual shall be allowed to “ oppress ” a
 60 UTILITY AND IMPORTANCE

 Accordingly,thetransactionsofsecularlife, furnish every day a practical refutation of the
objection which I am now considering. Does the head of a family,when a person applies to
be received as a resident under his roof,ever doubt that he has a right to inquire whether
the applicant be willing to conform to the rules of his family or not; and ifhe decline
this conformity, to refuse him admission ? And even after he has been received and
tried,for a while, if he prove an uncomfor table inmate,does not every one consider the master of the family as at liberty to exclude him? Hasnoteveryparent,and,ofcourse, every voluntary association of parents,an ac
knowledged right to determine what qualifi cations they will require in a preceptor for their children;and,ifso,tobring all candi dates to the test agreed on,and to reject those who do not corrrespond with it? And ifa candidate w h o fell totally short of the qualifi cations required,and who,of course,was re jected, should make a great outcry, that he
wantonly” and “ tyrannically” depriv
 OF CREEDS AND CONFESSIONS. 61
church? Surely it cannot be necessary to wait for an answer .
was
6

 ed of the place to which he aspired, would not every one think him insane, or worse than insane? The same principle applies to
every voluntary association, for moral, lite rary,orotherlawfulpurposes. Ifthemem
bers have not a right to agree on what princi ples they will associate, and to refuse m e m bership to those who are known to be entirely
hostile to the great object of the association, there is an end of all liberty. Of the self evident truth of all this, no one doubts. But where is the essential difference between any one of these rights, and the right of any c o m munity of professing Christians to agree upon what they deem the scriptural principles of their o w n union ; and to refuse admission into
their body of those w h o m they consider as unfriendly to the great purposes of truth and edification, for the promotion of which they associated? To deny them thisright, would be to make them slaves indeed !
It will probably, however, be alleged, that a church cannot, properly speaking, be con sidered as a voluntary association; that it is a community instituted by the authority of Christ;thatitslaws are given by Him,asits
 62
UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 63
 sovereignHead and Lord;andthatitsrulers
are in fact only stewards, bound to conform
themselves in all that they do to his will ; that,
if the church were their own, they would
have a right to shut out from it w h o m they
pleased; but as it is Christ's,they must find
some other rule of proceeding than their own
volitions. This is, doubtless, all true. The church of Christ certainly cannot be regarded
as a mere voluntary association, in the same
sense in which many other societies are so called. It is the property of Christ. His
will is the basis and the law of its establish
ment,and,of course, none can be either ad
mitted or excluded but upon principles which
his own word prescribes. This,however, it
is conceived,does not alter “ one jot or tittle,"
the spirit of the foregoing reasoning. The union of Christians in a church state, must,
still,from the nature of things,be a voluntary act; for if it were not so, it would not be a moral act at all. But if the union be volun tary,thenthose who form it,must certainly be supposed to have a right to follow their own convictions as to what their Divine M a s ter has revealed and enjoined respecting the

 and judging in any particular case? to the v applicants or delinquents themselves; or to the church in which membership is desired ?
If to the latter, on what principle is she bound
to proceed ? As her members have voluntarily associated for their mutual instruction and edi
fication in spiritual things, have they not a right to be satisfied that the individual who
appliestobereceivedamong them,eitherasa private member or minister,entertains opin ions,and bears a character,which will be con
sistent with the great object which they seek ? Can any such individual reasonably refuse to satisfy them as to the accordance of his reli gious sentiments with theirs,ifthey think that both the law of Christ, and the nature of the
 64 UTILITY AND IMPORTANCE
lawsoftheirunion. Iftheyarenottojudge
in this matter, w h o , I ask, is to judge for them ? Has the Head of the Church, then,
prescribed any qualifications as necessary for private membership,or for admission to the
ministerial office, in his church ? If so,what are they ? Will any degree of departure from the purity of faith or practice, be sufficient to excludeaman?Ifitwill,towhom hasour Lord committed the task of applying his law,

 OF CREEDS AND CONFESSIONS. 65
case, render such accordance necessary to Christian fellowship ? If he could not reason
ably refuse to give satisfaction verbally on this subject; could he,with any more reason,re fuse to state his own sentiments in writing, and subscribe his name to that written state
ment ? Surely to decline this while he con sented to give a verbal exhibition of his Creed, would wear the appearance of singular caprice or perverseness. But if no rational objection could be made to his subscribing a declaration, drawnupwithhisown hand,woulditnotbe exactly the same thing,as to the spirit of the transaction,if,with a view,simply,to ascer tain the fact of his belief, not to dictate laws to his conscience, a statement, previously
drawn up by the church herself, should be presented for his voluntary signature ? W h a t is required of an individual in such case is,not that he shall believe what the church believes;
but simply that he shall declare,as a matter of fact,whetherhedoespossessthatbelief,which, from his voluntary application to be received into Christian fellowship with that church , he
may be fairly presumed to possess. Again,I ask , is it possible to deny a church this right,
6*
 
 without striking at the root of all that is sacred in the convictions of conscience,and of all that
is precious in the enjoyment of Christian c o m munion ? I fully grant, indeed, that, as her authority rests entirely on the declared will of
Christ,she has no right, in the sight of God ,
to propose to a candidate, any other than a
sound orthodox Creed. She cannot possibly
be considered as having a right, on this prin
ciple, to require his assent to anti-scriptural
principles. Still, however, as the rights of conscience are unalienable; and as every
church must beconsidered,ofcourse,asverily
believing that she is acting according to her Master's will,we must concede to her the
plenary right,in the sight of man,to require from those who would join her, a solemn assent to her formularies.
But perhaps, itwill be asked,when a man has already become a member,or minister of a church, in virtue of a voluntary and honest subscription to her articles, and afterwards
alters his mind ; if he be excluded from her communion asaprivate member,or deposed
from office as a minister, is not here “ oppres sion?" Isitnotinflictingon aman a“heavy
 66 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS.
penalty” for his opinions;” “ punishing" him for his “ sincere, conscientious convic. tions?” Ianswer,iftheLordJesusChristhas not only authorized,but solemnly commanded
his church to cast the heretical, as well as
immoral,out of her communion,and wholly to withdraw her countenance from those who
preach " another gospel;" — then itismanifest,
that the church in acting on this authority, doesnooneanyinjury. Inexcludingapri vatemember from the communion ofachurch, or deposing aminister from office,in the regu lar and scriptural exercise of discipline, she deprives neither of any natural right. It is
only withdrawing that which was voluntarily asked, and voluntarily bestowed, and which
might have been,without injustice,withheld. It is only practically saying— “ You can no longer, consistently with our views,either of obedience to Christ, or of Christian edifica tion,be a minister or a member with us.
 67
may be as happy and as useful as you can in
any other connexion; but we must take away that authority and those privileges which w e once gave you,and of which your further exercise among us would be subversive of
You

 those principles which we are solemnly pledgedtosupport.” Isthislanguageunrea sonable ? Is the measure which it contem
platesoppressive? Would itbemorejustin itself, or more favourable to the rights of conscience,ifanyindividual could retainhis
placeasateacherand guideinachurch,con trary to its wishes; to the subversion of its
faith; to the disturbance of its peace; and finally to the endangering of its existence; and all this contrary to his own solemn en gagements,and to the distinct understanding
ofitsmembers,when hejoinedthem?Surely every friend of religious liberty would indig nantly answer, N o ! Such a church would be
the oppressed party,and such a member,the tyrant.
The conclusion,then,is,thatwhen achurch makes use of a Creed in the manner that has
been described ; as a bond of union ; as a bar rier against what it deems heresy; and in conformity with what it conscientiously b e lieves to be the will of Christ; it is so far from encroaching on the “ rights" of others; so far from being chargeable with “ oppres
-sion ;" that it is really, in the most enlight
 68 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 69
ened manner,and on the largest scale,main taining the rights of conscience ; and that for
such a church , instead of doing this, to give up its own testimony to the truth and order of
God's house; to surrender its own comfort, peace,and edification,for the sake of comply
ing with the unreasonable demands of a cor rupt individual,would be to subject itself to
theworstofslavery. Whatisthesubjugation
of the many, with all their interests,rights,
and happiness to the dictation of one,or a few , but the essence of tyranny?
 3. A third objection often urged against subscription to Creeds and Confessions is,that it is unfriendly to free inquiry.
66When a man ,” say the enemies of Creeds, “ has once
a public formulary, and taken his
subscribed
ecclesiastical
quires it,he must continue so to believe to
stand with a church which re
the end of life or resign his place; new light inabundance may offeritselftohisview;but hemustclosehiseyesagainstit. Now,can
itbe right,” say they, “ for any one volunta
rily to place himself in circumstances
of so
much temptation; willingly to place himself within the reach of strong inducements to

 70 UTILITY AND IMPORTANCE
In answer to this objection, m y first remark
is,that when a man takes on himself the so
lemn and highly responsible office of a public
instructer of others,we must presume that he
has examined the most important of the va
rious Creeds,called Christian,with all the de
liberation,sincerity,and prayer,of which he
is capable,and that he has made up his mind
with respect to the leading doctrines of Scrip
ture. To suppose any one capable ofentering on the duties of the ministerial office while he
is wavering and unsettled, and liable to be
“ carried about by every wind of doctrine,” is to suppose him both weak and criminal to a
very great degree. I know,indeed,that some ardent opposers of Creeds, consider a state of entire indecision with regard even to leading theological doctrines,as the most laudable and desirable state of mind. They wish every man ,not only to feel himself a learner to the end of life,which is undoubtedly right; but,
also,ifpossible,to keep himself in that equi librium of mind with respect to the most i m
portant doctrinal opinions,which shall amount
 tamper with conscience,and to resist convic tion ?”

 OF CREEDS AND CONFESSIONS. 71
to perfect indifference whether he retains or relinquishes his present sentiments. This they eulogize,as "openness to conviction,” “ free
dom from prejudice,” &c.
are
ever learning,and never able to come to theknowledgeofthetruth.” Irepeatit,we must suppose him who undertakes to be a teacher of others, to be himself, as the apostle expresses it, “ grounded and settled in the faith.” W e ought to be considered,then,as having all the security that the nature of the
case admits,that he who comes forward asone of the lights and leaders of a religious c o m m u nity, is firm in the principles which he has professed,and will not be very apt,essentially, toalterhisCreed.
But further; the same objection might be urged, with quite as much force, against a man's making any public declaration of his sentiments,either by preaching,or by writing, and printing; lest he should afterwards obtain
 Without stopping to combat this sentiment at large,I hesitate
not to pronounce it unreasonable
in itself;
contrary to Scripture; and an enemy to all
Christian stability and comfort. We know w h a t is said in the w o r d of G o d , of those w h o
66

 72
UTILITY AND IMPORTANCE
more light,and yet be tempted to adhere, con trary to his conscience,to what he had before
so publicly éspoused. But does any honest minister of the Gospel think it his duty to forbeartopreach,or otherwiseto expresshis
opinions,because it is possible he may after wards change them? We know that ifthe
preacher of a Unitarian congregation should alter his views,and become orthodox, he must quit his place, give up his salary, and seek employment among his new connexions.
The same thing would happen,ifa change the converse of this were to occur,and an ortho
dox preacher become a Unitarian.
 then? Because an honest man, when he changes his mind on the subject of religion,
will always hold himself in readiness to change his situation, and to make every necessary
sacrifice,shallhe,therefore,never venture to take any public station, lest he should not always think as he does at present ?
What
Nay,this objection,ifitprove anything,
will be found to prove by far too much even for our opponents themselves. The adversa ries of Creeds acknowledge, with one consent,
that every one ought to be ready to profess

 OF CREEDS AND CONFESSIONS. 73
hisbeliefintheBible. Butisnoteventhis
profession just as liable to the charge of being sunfriendly to free inquiry” as any other? Suppose any one,after solemnly declaring his belief in the Bible,should cease to believe it? Would he be bound to consider his old sub
scription as still binding, and as precluding further examination? Or would it be reason
able in any man to decline any profession of belief inthe Bible,lest he should,one day,
alter his mind,and feel himself embarrassed b y his profession ?
 There can be no doubt, that every public
act,by which a man pledges himself,even as a private member,to any particular denomi
nation of Christians,interposes some obstacle in the way of his afterwards deserting that
denomination,and uniting himself with ano ther. And,perhaps,itmay besaid,themore delicate and honourable his mind, the more reluctant and slow he will be to abandon his old connexions, and choose new ones. So
that such an one will really labour under a temptation to resist light, and remain where he is. But because this is so, shall a man
therefore, never join any Church ; never take
7

 74 UTILITY AND IMPORTANCE
one step that will, directly or indirectly, pledge his religious Creed or character, lest he should afterwards alter his mind,and be constrained to transfer his relation to a differ ent body,and thus be liable to find himself embarrassed by his former steps? Upon this principle,we must go further, and adopt the
doctrine equally absurd and heathenish, that no parent ought ever to instruct his child in
what he deems the most precious truths of the Gospel,lesthe should fillhis mind with pre judices, and present an obstacle to free and
unshackled inquiry afterwards. For there can be no doubt that early parental instruction does present more or less obstacle,in the way of a subsequent change of opinion, on those subjectswhich thatinstructionembraced. Yet our Father in heaven has expressly com manded us to instruct our children and to en deavour to pre -occupy their minds with every thing that is excellent both in principle and practice. In short,if the objection before us be valid, then no one ought ever to go for ward inthe discharge of any duty; for he
may one day cease to think it a duty; in other words, he ought habitually, and upon
 
 OF CREEDS AND CONFESSIONS. 75
principle, to disobey some of the plainest . commands of God , lest he should afterwards entertain different views of those commands, from those which he at present entertains. Nay, if this be so,then every book a man reads, and every careful, deep inquiry he makes concerning the subject of it, must be considered as tending to influence the mind, and to interfere with perfect impartiality in
any subsequent inquiry on the same subject; and,therefore,ought tobe forborne!
Surely no man in his senses judges or acts thus. Especially,no Christian allows himself thus to reason or act. In the path of what
appears to be present duty,he feels bound to
go forward, leaving future things with God.
If subscription to a correct Creed be really
agreeable to the will of God ; if it be necessa
ry, both to the purity and harmony of the
Church;and,therefore,initselfaduty;then,
no man ought any more to hesitate about dis
charging thisduty,than about discharging any
of those duties which have been mentioned,
or any others which may be supposed. There is no station in life in which its occupant does
notfindsomepeculiartemptation. Butifhe
 
 be a man of a right spirit, he will meet it with Christian integrity,and overcome it with
Christian courage. If he be a truly honest man,hewillbefaithfultohisGod,and faith
ful to his own conscience,at all hazards; and ifhe be not honest,he will not be very likely
to benefit the Church by his discoveries and speculations. Accordingly, the voice of his
tory confirms this reasoning. On the one hand,how many thousand instances have the lasttwo centuriesafforded,of men who were willing to incur, not only obloquy and re proach,but also beggary, imprisonment,and even death itself,in their most frightful forms, rather than abandon the truth, and subscribe to formularies which they could not conscien tiouslyadopt! Ontheotherhand,howmany instances have occurred,within the last fifty years,ofunprincipled men,aftersolemnlysub scribing orthodox Creeds, disregarding their vows,and opposing the spirit of those Creeds, and still retaining their ecclesiastical stations, without reserve! It is plain,then,that this whole objection,though specious,has not the
least solidity. Truly upright and pious men will always follow their convictions; while,
 76
UTILITY AND IMRORTANCE

 OF CREEDS AND CONFESSIONS. 77
with regard to those of an opposite character,
their light, whether they remain or depart, will be found to be of no value, either to themselves,ortheChurch ofGod.
Creeds
at all,or have long since professedly omitted to enforce subscription to them. To mention
only two examples: the Church of England, for nearly three centuries, has had a set of Articles decisively Calvinistic,to which all her candidates for the ministry are required to subscribe; but we know that more than a hun dred and fifty years have passed away,since Pelagian and Semi-Pelagian tenets began to pollute that important branch of the reformed Church ; and that within the last seventy -five or eighty years,almost every form of heresy has lurked under subscription to her orthodox Articles. And even the Church of Scotland,
 7*
any
4. A fourth objection frequently brought
against Creeds is, that they have altogether
failed of answering the purpose professed to
be intended by them. “ Churches," itissaid, which have Creeds the most carefully drawn ,
and of the most rigid character, are as far
from being united in doctrinal opinions, as some which either have never had

 which has had,for nearly two centuries,the
most rigidly and minutely orthodox Confes
sion on earth,is generally supposed, at this
hour,to have a ministry far from being unani
mous in loving and honouring her public
standards. N o w , if Creeds have not in fact,
been productive of the great benefit intended
by them ,even in some of the most favourable
cases that can be produced , w h y be perplexed and burdened with them at all?”
This objection evidently proceeds on the principle,that a remedy which does not ac complish every thing,is worth nothing. B e
cause Creeds have not completely banished dissension and discord from the churches
which have adopted them , therefore they have been of no use. But isthis sound rea soning? Does itaccordeven with common
sense, or with the dictates of experience in any walk oflife? Because the Constitution of the United States has not completely defended our country from all political animosity and strife, is it,therefore,worthless? Or should we have been more united and harmonious without any constitutional provisions at all? Because the system of public law does not a n
 78
UTILITY AND IMPORTANCE
1
1

 OF CREEDS AND CONFESSIONS. 79
 nihilateallcrime,shouldwe,of course,beas wellwithoutit. No onewillsaythis. Nay, may not the objection be retorted on those who urge it? They contend that Creeds are unnecessary; that the Bible isamply sufficient
for all purposes, as a test of truth. But has the Bible banished dissension and discord from the Church ? N o one will pretend that it has. Yet w h y not ? Surely not on account ofany error or defect in itself; but on account of the folly and perverseness of depraved m a n , w h o , amidst all the provisions of infinite wisdom and goodness,is continually warring against the peace of the world .
But I go further, and maintain that the his tory of the practical influence of Creeds, is strongly in their favour. Though they have
not done every thing that could have been
desired,they have done much ; and much in
those very churches which have been most
frequently selected as examples of their entire want of efficacy. The Calvinistic articles of
the Church of England were the means of keeping her doctrinally pure, to a very re markable degree, for the greater part of a
hundred years. In the reign of James I.,

 80 UTILITY AND IMPORTANCE
very few opponents of Calvinism dared p u b licly to avow their opinions; and of those who
did avow them, numbers were severely disci plined, and others saved themselves from
similar treatment, by subsequent silence and discretion. The inroads of error, therefore,
were very powerfully checked, and its tri
umph greatly retarded by those public stand
ards. In fact, the great body of the bishops
and clergy professed to be doctrinal Calvinists,
until a number of years after the Synod of Dort,when,chiefly by the influence of Arch
bishop Laud,and his creatures,Arminianism was gradually and guardedly brought in, in consequence of which the faithful application
of the thirty-nine articles,as a test of ortho doxy,and of admission to the ministry,was discontinued. Thearticlescontinuedtospeak
as before, and to be solemnly subscribed ; but the spirit of the administration under them was no longer the same. It became predomi nantly Arminian. W e may truly say,then, thattheCreedoftheChurchofEngland con
tinued to operate effectually as a bond of union, and a barrier against the encroach mentsof heresy, as long as it continued to be
 
 OF CREEDS AND CONFESSIONS. 81
faithfully applied,agreeably to its known ori ginal purport. W h e n it ceased to be thus applied, it ceased to produce its wonted effect. But can this be reasonably wondered at? As well might we wonder that a medicine,when its use was laid aside,should no longer heal.
The very same representation,in substance, may be made concerning the church of Scot land. Herpre-eminentlyexcellentCreedwas
the means,under God,of keeping her united
and pure,as long as that Creed continued to
be honestly employed as a test,according to
its true intent and spirit. W h e n this ceased to be the case, it would have been strange,
indeed,if the state of things had remained as before. Itdidnotsoremain. Withlaxand
dishonest subscription, heresy came in:--at first,with reserve and caution,but afterwards more openly . But even to the present day, as all know who are acquainted with the state ofthatchurch,themovementsofheresywithin her bosom, are held in most salutary check; and her condition is incomparably more fa vourable than it could have been, had her public standards been long ago abolished.
Nor have the Creeds of those national
 
 82 UTILITY AND IMPORTANCE
Nor are we without significant attestations to the efficacy of Creeds, and to the mischief
of being without them,in our own country. Of the former, the Presbyterian church in the United States,isone of the most signal exam ples. Conflictsshehas,indeed,had;butthey
 churches of Great Britain yet accomplished
all the benefits to the cause of truth and right
eousness which they are destined to confer.
Though their genuine spirit has been long
sinceforgotten by many;thisisby no means thecasewithall. Therehasconstantlybeen
in both those churches, a body of faithful wit nessestothetruth. Thisbody,thankstothe Almighty and all-gracious King of Zion ! is increasing. Their “ good Confessions” form a rallying point, around which numbers are now gathering; and those far-famed forinu laries, the favourable influence of which has been supposed by many to be long since ex
hausted,and more than exhausted,will again become, there is every reason to believe,an
ensign to the people,” to which there shall be a flocking of those who love the “ simpli city that is in Christ,” more extensive and more glorious than ever before.

 OF CREEDS AND CONFESSIONS. 83
5. The last objection which I shall consider is, that subscription to Creeds, has not only failed entirely of producing the benefits con templated by their friends; but has rather been found to produce the opposite evils;—to generate discord and strife.
 have been such as were incident to every
community, ecclesiastical or civil, adminis
tered by the counsels of imperfect men.
Amidst them all, she has, by the favour of
her Divine Head,held on herway,substan
tially true to her system of doctrine and
order; and though constituted, originally, by
members from different countries,and of dif
ferent habits, she has remained united to a
degree, considering all things, truly w o n d e r
ful. Of the latter,the Congregational churches
of Massachusetts,furnish a melancholy m e m o
rial. Though originally formed by a people, far more homogeneous in their character and
habits,and far more united in their opinions; yet, being destitute of any efficient bond of
union,and equally destitute of the means of maintaining it,if it had been possessed,they have fallen a prey to dissension and error,to a degree, equally instructive and mournful.
“ Creeds," say

 84 UTILITY AND IMPORTANCE
some, “ instead of tending to compose diffe rences,and to bind the members of churches
more closely together, have rather proved a bone of contention, and a means of exciting
mutual charges of heresy,and a thousand ill feelings,among those who might have been
otherwise perfectly harmonious."
In reply to this objection, m y first remark
is, that the alleged fact, which it takes for
granted,isutterlydenied. Itisnottruethat
Creeds have generated contention and strife
in the bosom of those churches which have
adopted them. On the contrary,itwould be easy to show , by an extended induction of
facts, that in those churches in which Creeds and Confessions have been most esteemed and
most regarded, there union and peace have most remarkably reigned. In truth, it has ever been the want of faithful regard to such formularies, that has led to division and strife intheChurchofChrist. Idoubtwhether
 denomination of Christians ever existed, for
half a century together, destitute of a public Creed, however united and harmonious it
might have been, at the commencement of thisperiod;withoutexhibiting,beforetheend
any

 OF CREEDS AND CONFESSIONS. 85
ofit,eitherthatstillnessofdeath,which isthe
result of cold indifference to the truth ; or that
miserable scene of discord,in which parting
asunder” was the only means of escaping from open violence.
My nextremarkis,that,evenifitwere shown,that orthodox public Creeds are often indirectly connected with conflict and conten
tion in the Church ; it would form no solid
argument against them. Ardent attachment
to what they deemed truth,is the principle,in
allages,which has led Christian communities
to adopt Creeds and Confessions of Faith.
The same attachment to truth will naturally lead them to watch with care against every
thing that is hostile to it; and to “ contend earnestly ” in its defence, w h e n it is attacked .
In this case, a Creed, supposing it to be a sound and scriptural one, is no
 more the cause of conflict and division,than a whole
some medicine which it is intended
God commands
is the cause of that disease to cure. The word of us to " contend,” and to
« contend earnestly, for the faith once deliv ered to the saints," and to hold him “ accurs
ed” who preaches “ another gospel” than that
8

 which the Scriptures reveal. But when such 6 contention” becomes necessary, who is to
blame for it? Surely not truth, or its advo cates; but those who patronise error,and thus
endeavour to corrupt the body of Christ;and, of course render contention for the truth a
duty. Itisgranted,indeed,that,inthiscon flict,much unhallowed temper may be mani fested. Notonlyonthepartoftheadvocates of error;but also,in some degree,on the part of the friends of truth. They may contend even for the truth, with bigotry and bitter ness. Still, this does not render the truth
itselfless precious; or the duty of contending for it less imperative; or those summaries of it which Christians have been led to form , less valuable,as testimonies for God .
 86 UTILITY AND IMPORTANCE
Before Christianity was preached in the
Roman empire,the different classes of Pagans lived together in peace. The foundation of
this peace was the opinion, that error was in nocent ; and that all classes of religionists were equally safe. But when the religion of Jesus Christ was preached; when his minis ters proclaimed that there was no other system
either true or safe; that there was no other

 OF CREEDS AND CONFESSIONS. 87
foundation of hope ; that all false religions were not only highly criminal, but also eter nally destructive ; and that the followers of
Christ could not possibly countenance any of
them ;-thens a scene of the most shocking
persecution and violence, on the part of the
Pagans, commenced. But on what, or on
whom,are we to throw the blame,forthese
scenesofviolence? No one,surely,willsay,
on Christianity. W e are rather to impute it
to thecorruptionofhuman nature,and tothe
blindness and violence of Pagan malice. If
the primitive Christians had been willing to
give up the precious truth committed to them ,
and to act upon the principle,that all modes
of faith were equally safe; they might have
escaped much,if not the whole of the dread
ful persecution which they were called to en dure.
The only additional remark, therefore, which I have to make on the objection before us, is, that it can have no force, excepting upon the principle,that error ought to be left unassailed, and that contention for the truth
is not a duty :—for all defence of the truth, against its active opposers — all “ contending
 
 for the truth," must, of course, disturb that cold and death-like tranquillity which indif
ference to the purity of faith tends to intro
duce. We arecommanded,“ifitbepossible,
as much as lieth in us,to live peaceably with
allmen.” But itisnot possible” to be at peacewithsomemen. We mustnotbeat
peace with error or wickedness. The Divine authority makes it our duty to oppose them
totheutmostatourperil. Andif,inthedis charge of this duty,the peace of the church is, for a time, disturbed, the sin lies at the door of those who rendered the conflict neces sary. Those summaries of truth,which par ticular occasions m a k e it important to e m b o d y and to publish,are no more to blame for the struggle,than the wise and wholesome law of
the land is to blame for that agitation which
necessarily attends the seizure, the trial, and the execution of a malefactor.
 88 UTILITY AND IMPORTANCE
But admitting Creeds to be lawful and ne cessary,ithas often been asked by some who profess to be their friends,whether they ought ever to contain any other articles than those f e w w h i c h a r e s t r i c t l y f u n d a m e n t a l ;- i n o t h e r

 OF CREEDS AND CONFESSIONS. 89
 words,whetherwe oughtevertoinsertamong the members of a Creed intended to be sub
scribed by all candidates for office in a church, any more than some half a dozen articles, the reception of which is generally considered as absolutely essential to Christian character ?
This is a question of real importance,which
certainly deserves grave consideration,and a candid answer. And for one,I have no hesi
tation in saying, that in m y opinion, church Creeds not only lawfully m a y , but always ought, to contain a number of articles besides those which are fundamental. And to estab
lish this, as it appears to m e , no other proof is necessary than simply to remark , that there
are many points confessedly not fundamental,
concerning which , nevertheless, it is of the
utmost importance to Christian peace and edi
fication,that the members,and especially the ministers of every church should be harmo
niousintheirviewsandpractice. Aslongas the visible church of Christ continues to be
divided into different sections or denomina
tions,the several Creeds which they employ, if they are to answer any effectual purpose at all,must be so constructed as toexclude from
8*

 each those teachers w h o m it conscientiously
believes to be unscriptural and corrupt ; and
w h o m ,as long as it retains this belief, it ought to exclude.
To exemplify my meaning. The Presby terian church,and most other denominations, who have a regular system of government, believe that the Christian ministry is a divine ordinance,and that none but those who have
been regularly authorized to discharge its functions,ought by any means,to attempt to preach the Gospel, or administer the Sacra ments of the church. Yet there are very pious,excellent men,who have adopted the sentiments of some high-toned Independents, who verily think that every “gifted brother," whether ordained or not,has as good a right to preach as any man ; and,if invited by the church to do it,to administer the Sacraments. N o w ,no sober minded Presbyterian will con siderthisasafundamentalquestion. Funda mental, indeed, it is, to ecclesiastical order; but to the existence of Christian character, it is not. M e n m a y differ entirely on this point, and yet be equally united to Christ by faith, and,of course equally safe as to their eternal
 90 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 91
Take another example. No man in his senses will consider the question which di vides the Pedobaptists and the Antipedobap tists as a fundamental one. Though I have no doubt that infant baptism is a doctrine of the Bible,and an exceedingly important doc
 prospects. But would any real, consistent Presbyterian be willing to connect himself with a church,calling itself by that name,in which,while one portion considered none but a regular minister as competent to the dis charge of the functions alluded to, as m a n y of
the other portion as chose, claimed and actu ally exercised the right,to rise in the congre
gation, and preach,baptize, and dispense the Lord's Supper, when and how each might think proper; and not only so,but when the
ordained ministers occupying the pulpit, in succession, differed no less entirely among themselves in reference to the disputed ques
tion;some encouraging,and othersrepressing, the efforts of these “ gifted brethren ? I do not ask whether such a church could be tran
q u i l o r c o m f o r t a b l e ; b u t w h e t h e r it c o u l d p o s sibly exist in a state of coherence,for twelve months together ?

 trine;and thatthe rejectionofitisamis
chievous error; yet Ihave quite aslittledoubt that some eminently pious men have been of a different opinion. But what would be the situation of a church equally divided,or nearly
so,on this point; ministers as well as private members constantly differing among them
selves; members of each party conscientiously persuaded that the others were wrong ; each laying great stress on the point of difference, as one concerning which there could be no
compromise,or accommodation;all claiming and endeavouring to exercise the right not only to reason,but to act,according to their respective convictions;and every one zealous ly endeavouring to make proselytes to his own principles and practice? Which would such a church most resemble— the builders of Babel,when their speech was confounded; or a holy and united family, “ walking together inthefearoftheLord,andintheconsolations
of the Holy Ghost,and edifying one another in love?"
Let me offer one illustration more. The question between Presbyterians and Prelatists is generally acknowledged not to be funda
 92 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 93
mental. I do not mean that this is acknow
ledged by such of our Episcopal brethren as
coolly consign to what they are pleased to call
the “ uncovenanted mercy ofGod," allthose denominations who have not a ministry epis
copally ordained ; and w h o , on account of this
exclusive sentiment are styled by Bishop A n
drews, “ iron hearted,” and by Archbishop
Wake, “madmen:” but my meaning is,that
all Presbyterians, without exception ; a great
majority of the best Prelatists themselves;
and all moderate,sober-minded Protestants,of
every country,acknowledge that this point of
controversy is one which does by no means affectChristiancharacterorhope. Stillisit
not plain, that a body of ministers entirely differing among themselves as to this point; though they might love,and commune with, each other,as Christians; could not possibly act harmoniously together in the important rite of ordination ; whatever they might do in other religious concerns ?
In all these cases, it is evident there is n o
thing fundamental to the existence of vital
piety. Yet it is equally evident, that those w h o differ entirely and zealously concerning
 
 But for further details on this subject, both for and against the doctrine which I maintain, I must refer you to those works which have been devoted to its more extended discussion: more particularly to what is said by the judi cious and excellent Mr. Dunlop,in the able
 94 UTILITY AND IMPORTANCE
the points supposed,cannot be comfortable in the same ecclesiasticalcommunion. But how
is their coming together,and the consequent
discord and strife, which would be inevitable, tobeprevented? Iknowofnomethodbut so constructing their Confessions of Faith as to form different families or denominations, and to shut out from each those who are hos
tile to its distinguishing principles of order. It is plain,then,that unless Confessions of Faith contain articles, not, strictly speaking,
fundamental, they cannot possibly answer one principal purpose for which they are formed,
viz.guarding churches which receive the pure order and discipline, as well as truth, of Scripture,from the intrusion of teachers,who, though they may be pious, yet could not fail to disturb the peace,and mar the edification of the more correct and sound part of the body.

 OF CREEDS AND CONFESSIONS. 95
Preface to his “ Collection of Confessions:" to
“ The Confessional," by Mr. Blackburn,one of the most zealous and formidable opposers
of Creeds; which will prepare you for peru sing some of the best of the many valuable answers tothatfar-famed work:to “Walker's Vindication of the Church of Scotland,” & c: and,finally,to Mr. Dyer's “ Inquiry into the Nature of Subscription to Articles of Reli
gion.”
The subject, beloved Pupils, on which I have been addressing you, is eminently a practical one. It enters deeply into many questions of personal and official duty. I shall, therefore, detain you a few moments longer, by calling your attention to some of those practical inferences from the foregoing principles and reasonings,which appear to me to deserve your serious regard - and
1. From the representation which has been
given,we may see how little reason any have to be afraid of Creeds as instruments of o p
pression.
 There is something so perfectly visionary and unreasonable in the very thought of " t y

 96 UTILITY AND IMPORTANCE
ranny,” or “ oppression ,” as connected with
subscription to Creeds, in this country, that
the only wonder is,how it can be admitted, for a moment,into any sober mind. Who
does or can impose a creed upon any one,or ever attempt to do it? Is any man in the
United States obliged to profess any belief; to subscribe any Creed ; or to join any church
whatever ? Every man , indeed, is bound by the law of God , to believe correctly, and to connect himself with a pure church. He is
not and cannot be at liberty,in the sight of
Jehovah,to neglect either. But is any man
bound by human law,ecclesiastical or civil,to
do any of these things? Is any man in the
United States,after he has subscribed a Creed,
and joined a church, obliged, by any human
authority, to adhere to either a single day
longer than he pleases? Is he not at perfect
liberty to withdraw ,at any moment,and that
with or without giving a reason for his con duct, as he thinks proper ? Everlasting thanks
to H i m w h o gives us this freedom ! M a y it be perpetual and universal! Now , one would
think, this is liberty enough to satisfy any reasonableman. Butitseemstherearereally
.
 
 OF CREEDS AND CONFESSIONS. 97
those who wish for more. They demand,in effect, that the church should be willing to
take all manner of heresy, as well as ortho doxy, to her bosom, and to act as if she
regarded both with an equal eye. Nay,they ask that heretics be freely allowed to impose
themselves upon her,whether she be willing or not - not to unite and edify her members, but to divide and distract them ;—that they be
at liberty to come into the Redeemer's family, and there,without any regard to itsscriptural
rules,or itshappy harmony,topropagate such discordant sentiments, and to establish such new principles of order, or disorder, as the intruders may choose to adopt. But is this Christian liberty? Is this a kind of liberty which any benevolent, or even honest man wouldwish topossess?Itisliberty,trulyof the most extraordinary kind,to the individu al who intrudes; but what becomes of the liberty of the ecclesiastical body which he thus enters, contrary to its wishes and c o m fort, and to its real injury? It is, evidently, the same sort of privilege in the church,as the privilege of invading the retreat of private families, or disturbing the peace of civil soci
 9

 98 UTILITY AND IMPORTANCE
ety, at pleasure, and with impunity , would be regarded by the inhabitants of any free country.
2. W e may see from what has been said, that subscribing a Church Creed,is not a mere formality; but a very solemn transaction, which means much,and infersthemostseri ous obligations. It is certainly a transaction which ought to be entered upon with much deep deliberation and humble prayer; and in which,ifa man be bound to be sincere in any
thing, he is bound to be honest to his God, honest to himself,and honest to the Church
which he joins. For myself, I know of no transaction,in which insincerity is more justly
chargeable with the dreadful sin of " lying to the Holy Ghost," than in this. It istruly
humiliating and distressing to know,that in some churches ithas gradually become custom ary, to consider Articles of Faith as merely articles of peace; in other words, as articles which he who subscribes,is not considered as professing to believe ; but as merely engaging not to oppose--at least in any public or offen sive manner. Whether we bring this princi
ple to the test of reason , of Scripture, of the
 
 OF CREEDS AND CONFESSIONS. 99
original design of Creeds, or of the ordinary import oflanguage among honourablemen ; it seems equally liable to the severest repro bation, as disreputable and criminal in a very
highdegree. Nordoesitappeartometobe any alleviation, either of the disgrace or the
sin,thatmany ofthegovernorsofthechurches
referred to, as well as of those w h o subscribe,
publicly avow their adoption of this principle;
admit the correctness of it; keep each other
in countenance; and thus escape,as they ima
gine,the charge of hypocrisy. What would
be thought of a similar principle, if generally adopted and avowed,with respect to the ad
ministration of oaths in civil courts ? Suppose both jurors and witnesses,feeling it a griev ance to be bound by their oaths to speak the truth, were to agree among themselves, and openly to give out, that they did not mean, when they swore,to take on themselves any such obligation; that they did not so under
stand the import of their oaths, and did not intend to recognize any such meaning ? A n d suppose the judges were freely to admit them to their oaths with a similar understanding ? Would awitnessor ajuror,insuchacasebe
 
 exempt from the charge of perjury, or the
judge from the guilt of subornation of per
jury? I presume not,in the estimation of any sobermindedman. Ifitwereotherwise,then
badmen,who formamajorityofeverycom munity,might, by combining, violate all the
principles of virtue and order, not only with impunity,but also without sin.
Set it down, then, as a first principle of common honesty,aswellasofChristiantruth,
that subscription to Articles of Faith, is a
weighty transaction, which really means what
it'professes to mean ; that no man is ever at
liberty to subscribe articles which he does not
truly and fully believe; and that, in subscri
bing,he brings himself under a solemn,cove nant engagement to the church which he
enters,towalkwith it"intheunityoffaith,"
and " in the bond of peace and love." If he cannot do this honestly,let him not profess to do it at all. I see not but that here, insince rity,concealment, double dealing,and mental reservations, are, to say the least, quite as mean and base as they can be in the transac tions of social and civil life.
You will, perhaps, ask me, what shall be
 100 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 101
other Church on earth? I again answer- by no means. Iknowofnoothermodeofproceed
ing in such a case as this,which Christian can dour,and a pure conscience will justify, than the following: Let the candidate for admission
unfold to the Presbytery before which he pre sents himself, all his doubts and scruples,with perfect frankness; opening his whole heart, as if on oath ; and neither softening nor con cealing any thing. Let him cause them dis tinctly to understand,that if he subscribe the
 done by a man who loves the Presbyterian Church; who considers it as approaching
nearer to the scriptural model than any other with which he is acquainted; who regards its
Confession of Faith as by far the best,in its greatoutlines,and in all itsfundamental arti cles,thathe knows;andwhoyet,insomeof its minor details cannot entirely concur ? Can such an one honestly subscribe, without any previous explanation of his views ? I a n s w e r bynomeans. Oughthe,then,youwillask,
to abandon all thoughts of uniting himself with our Church , when he is in cordial harmony with it in all fundamental principles, and
nearertoit,in allrespects,thantoany
9*

 Confession of Faith, he must be understood to do it in consistency with the exceptions and explanations which he specifies. If the Pres bytery,after this fair understanding,should be of the opinion,that the excepted points were of little or no importance,and interfered with no article of faith, and should be willing to receive his subscription in the usual w a y , he
may proceed. Such a method of proceeding will best accord with every principle of truth and honour; and will remove all ground of either self-reproach,or of reproach on the part
of others, afterwards.
 102 UTILITY AND IMPORTANCE
3. From the view which has been presented
ofthissubject,we may decide how an honest m a n ought to act, after subscribing to a public creed. H e will feel it to be his duty to adhere
sincerely and faithfully to that Creed,in pub
lic and in private; and to make ithis study to
promote,by all means in his power,the peace
and purity of the body with which he has con nectedhimself. And ifheshould,atanytime,
alter his views concerning any part of the Creed or order of the Church in question,it
will be incumbent on him to inquire,whether the points, concerning which he has altered

 OF CREEDS AND CONFESSIONS. 103
hismind,areof suchanature asthathe can conscientiously be silent concerning them,and
“ give no offence" to the body to which he belongs. Ifhecanreconcilethiswithanen
lightened sense of duty,he may remain in peace. But ifthe points concerning which his views have undergone a change, are of so much importance in his estimation,as that he cannot be silent,but must feel himself bound to publish,and endeavour to propagate them ; then let him peaceably withdraw,and join. some otherbranchofthevisibleChurch,with which he can walk harmoniously. Such he may find almost every where,unless his views
be singularly eccentric. But,at any rate,he has no more right to insist on remaining, and being permitted publicly to oppose,what he has solemnly vowed to receive and support; than a member of any voluntary association, which he entered under certain engagements, but with which he no longer agrees, has a
right obstinately to retain his connexion with
it,and to avail himself of the influence which
his connexion gives him,to endeavour to tear it in pieces.
It is no solid objection to this view of the
 
 104 UTILITY AND IMPORTANCE
subject,toallege,thatevery man isunder ob ligations to obey the great Head of the Church, altogether paramount to those which bind him , in virtue of any ecclesiastical engagements,to
obey the Church herself. This is most readily granted. No man can lawfully bind himself
to disobey Christ,in any case whatever. But
this principle,it is conceived,has nothing to do with the point under consideration. Though a m a n cannot properly bind himself always to believe as he now believes; nor always to re main in connexion with the ecclesiastical body which he now joins; yet he may safely pro mise that he will be a regular and orderly
member of the body,as long as he does re main in connexion with it. W h e n he ceases
to be able to do this, without sinning against
God,he will,if he be an honest man, imme
diately withdraw. If he remain, and suffer himself habitually to violate his engagement,
under the pretence of benefitting the body to which he has vowed allegiance, he will be chargeable with the sin of treacherously and basely “ doing evil that good may come.”
 T o illustrate m y m e a n i n g b y a familiar e x ample. Every student of this Seminary has,

 OF CREEDS AND CONFESSIONS. 105
at his entrance,made asolemn promise,that as long as he shall continue a member of it, he will conscientiously and vigilantly observe all the rules and regulations specified in the plan for its instruction and government, so far as the same relateto the students; and further, that he will obey all the lawful requisitions of the Professors and Directors,” & c. A s this
engagement was voluntarily made,no honest man will doubt that you areallbound toact
in conformity with it,to the utmost tittle,as far as you have ability. Suppose, however, that one of your number should become per suaded,that some of the " regulations speci fied in the plan ” of the Seminary, are not only unwise, and inconvenient, but also i m moral; what ought he to do ? Ought he to remain in the institution,and habitually vio late the regulations to which he excepted,
pleading that he could not conscientiously obey them,because, though he had solemnly engaged to do so,hefelt himself under a prior and paramount obligation to “ obey God rather thanman ?” This,surely,no Christian would approve, nor any faithful government tolerate. N o ; every principle of honour and integrity
 
 would dictate, that he should immediately withdraw from the Seminary;and if,after withdrawing, he should be able to convince the General Assembly of our Church,that his exceptions were just,and should prevail with that body to alter the offensive rules; then, a n d n o t till t h e n , h e m i g h t , w i t h a g o o d c o n
science, resume his place in the institution.
 106 UTILITY AND IMPORTANCE
the
4. W e are led to reflect,from the represen t a t i o n w h i c h h a s b e e n g i v e n , h o w e a s y it is f o r a single imprudent or unsound minister to
do extensive and irreparable mischief in the Church. Such an one,especially if he be a man of talents and influence,by setting him self, either openly or covertly, against the public standards of his Church ; by addressing popular feeling,and availing himself of popu larprejudice; may do more,in a short time, to prepare w a y for fatal error, than all his usefulness,though multiplied a hundred fold, wouldbeabletocountervail. Ministers,my young friends,may be said to hold in their
hands the interests of the Church,to a degree which no other class of men do;and which ought to make them tremble under a sense of theirresponsibility! Suchasisthecharacter

 OF CREEDS AND CONFESSIONS.
107
 ofthe ministry of any particular Church,will
be, generally speaking, the character of the
Church itself. On the one hand,iftheminis
ters of religion be generally enlightened, or thodox,holy,diligent,and faithful men,the
Church to which they belong,will never fail to display the influence of this character in happy results.
On the other hand,never was
the Church,in any country or age,corrupted, divided, and ruined, but the mischief was done by its ministers. However humiliating or painful this assertion may be,itis undoubt
edly confirmed by all Scripture,and all expe
rience. And as the general influence of the clerical character is so vital; so it is not easy
tomeasure themischiefthatmay bedone by
one unsound,graceless, imprudent, turbulent minister. If,ineverywalkof society,“one
sinner destroyeth much good,” how much more wide spread,deplorable,and fatal is the
mischief, when the criminal individual is a minister! By erroneous opinions; by corrupt habits; by a love of innovation; by embracing hinself, and extensively imparting to others, pernicious delusions;-he may do more in five or ten years,to agitate, divide, corrupt,

 108 UTILITY AND IMPORTANCE
Beloved Pupils! be it your study, at all times,to cherish a deep sense of your solemn responsibility to God and his Church. In a littlewhile,youwillbeamong thosetowhom the most weighty interests that can be c o m mittedtoman,willbeentrusted. Befaithful to your high trust. Guard, with the utmost
vigilance,the Church's orthodoxy. Nothing can be truly right,where her doctrinal prin ciples are essentially wrong. But,O,think not that mere frigid orthodoxy,however per
 and weaken the Church,than,perhaps,a score of the most faithful ministers in the land,can
do,humanly speaking,forpromoting its purity and peace,in half a century. The influence
of two or three individuals,of popular talents, in Massachusetts,more than fifty years ago,
in gradually undermining orthodoxy, and in
reconciling the public mind to heretical opi
nions, is as well known, as it is deeply de
plored,by many who are acquainted with the
ecclesiastical history of New England. The authors of this mischief have long since gone
to their account; but their works have sur vived them ; and of their awful ravages, no one can estimate the extent,or see the end.

 OF CREEDS AND CONFESSIONS. 109
fect,isallthatisneeded. Labourtodiffuse, in every direction; the holy and benign influ ence of truth. If t h e household of faith"
be corrupted by heresy,or torn by schism, or agitated by unhallowed innovation,or become
cold through want of ministerial faithfulness,
see to it, that none of you be found among the workers of the mischief. See to it that
you seek unceasingly, not “ your own things," your own aggrandizement,your own honour,
your own fancies, or your own speculations, but t h e things which are Jesus Christ's." If you cannot benefit the Church, (and no man has a right to say that he cannot, if he have a heart for the purpose) at least, do
not lend your influence to the,unhallowed
work of corrupting and dividing it. And if
you should ever be brought into circumstances
in which you can do nothing else, see that you be found, like the ministers of the
Lord” ofold,“weeping between theporch and the altar, and saying, spare thy people,
0, Lord, and give not thine heritage to re proach;savethem ,andliftthem up forever!”
5. W e may infer,from what has been said,
the duty and importance of all the members, 10
 
 and especially the ministers,of the Presbyte
rian Church,exerting themselves to spread a knowledge of her public standards. I say,
her “public standards,” notwithstanding all the sneer and censure which have been cast
on this language. For every intelligent and
candid man in the community knows that we
employ itto designate,not formularies which
w e place above the Bible ; but simply those which ascertain and set forth how we inter
pret the Bible. These formularies -- if they
be really an epitome of the word of God , and
surely we think them so — every minister is bound to circulate, with unwearied assiduity, among the people of his charge. This is so
far, in general, from being faithfully done,
that I seriously doubt, whether there be a
Protestant Church in Christendom ,in which
there is so striking a defect as to the discharge
of this duty, especially in some parts of the
country,asinthePresbyterianChurch. Our
Episcopal brethren exercise a most laudable
diligence in placing the volume which con tains their articles, forms,and offices, in every
family within their reach,which belongs to their communion, or can be considered as
 110 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 111
 tendingtowardsit. OurMethodistand Bap tist brethren , with no less diligence, do the same,with respect to those books which ex hibit the doctrines and order of their respec tive denominations. All this is as itshould be. It bespeaks men sincere in their belief,
and earnest in the dissemination of what they
deem correct principles? W h y is it that so
many ministers of the Presbyterian Church,
with a Confession of Faith,and Catechisms, which,I verily believe, and which the most
of them readily acknowledge, are by far the best that were ever framed by uninspired wisdom ;and with aForm ofGovernment and Discipline more consentaneous with apostoli
cal practice than that of any other Church on
earth, are yet so negligent, not to say so in different, as to the circulation of these f o r m u
laries? They,perhaps,do not take the trouble
even to inquire whether there be a copy of the volume which contains them , in every
family, or even in every neighbourhood, of theirrespectivecharges. How arewe toac count for the peculiar frequency of this negli
gence in the ministry of our Church ? It would befarfrom beingtrue,Itrust,to say,

 that our clergy are more unfaithful in the ge neral discharge of their duties,than those of any other communion. May we not rather ascribe the fact in question to another fact, from which it might be expected naturally to arise ? The fact to which I allude is,that,in
the Presbyterian Church,at the present day, and in thiscountry -whatever may have been the case in former times— there is less of sec
tarian feeling ; less of what is called, the esprit du corps,than in any other ecclesiasti cal body among us. W e are in truth,if I do not mistake,so excessively free from it,as to be hardly ready to defend ourselves when attacked. W e are so ready to fraternize with all evangelical denominations,that we almost forget that we have a denomination of our own, to which we are peculiarly attached. Now ,this general spirit is undoubtedly excel lent; worthy of constant culture, and the highestpraise. Butmayitnotbecarriedto an extreme ? Universal, active benevolence, is a Christian duty ; but when the head of a family,in the ardour of its exercise,feels no more concern or responsibility respecting his own household,than he does about the house
 112 UTILITY AND IMPORTANCE

 OF CREEDS AND CONFESSIONS. 113
forhim to desirethatothers should
viewitinthesamelight? Andifhebejus tifiable in recommending these peculiarities
from the pulpit—as all allow -is he not
equally justifiable in recommending them from the press,especially by means of accre dited publications ?
Happy willitbe forour Church,then,if her future ministry shall be more attentive to the duty in question,than many of those who have gone before them . To you, beloved Candidatesforthesacredoffice,letme recom mend a sacred regard to this duty. Resist,
 holds of others,he acts an unreasonable part,
and,what isworse,disobeys the command of God . Something analogous to this,I appre hend,is the mistake of that Christian,or that minister, who in the fervour of his catholi cism,loses sightof the fact,that God,in his providence,has connected him with a particu lar branch of the visible Church,the welfare and edificationof which he ispeculiarly bound to seek. If his own branch of the Church have any thing of peculiar excellence in his estimation, on account of which he prefers it—which is always to be supposed— can it
be
wrong
10*

 114 UTILITY AND IMPORTANCE
always,to the utmost of your power,the lit tlenessofsectarianbigotry,andstrivetobanish itfrom the Church. But,atthe sametime,
cherish among her members an enlightened attachment to that particular branch of the family of Christ in which their lot is cast. For this purpose, strive to promote among
them a general and intimate acquaintance with our Confession of Faith,and Form ofGovern
ment and Discipline,aswell as our Catechisms, which latter,I fain would hope,are not en tirely neglected in any part of the Church. Never advise the people to take the contents of these public formularies on trust; but dili gently to compare every part of them with Scripture,and see how far they agree with the unerring Standard. Thus will you be likely to become instrumental in forming solid,intel ligent Christians. Thus may you hope to become the spiritual fathers of multitudes, “ whose faith shall stand, not in the wisdom of m e n , b u t i n t h e p o w e r o f G o d .”
6. Once more ; if the foregoing principles be just,then how unhappy is the mistake of those who imagine, that by abandoning all Creeds and Confessions, they are about to
 
 OF CREEDS AND CONFESSIONS. 115
The apostle Peter thus exhorted the Chris iansinhisday:“Be sober,bevigilant,be
 render the Church an essential service; to build her up more extensively and gloriously than ever! There are those who imagine that a new order of things is about to open on the Church ,amounting to as great a change of dis
pensation as ever marked the progress of the Redeemer's kingdom,in any preceding age. In thisnew and undefined prospect,they seem to themselves to see the approaching prostra tion of most of those fences,and the dissolu tion of most of those ties,which have hereto fore been regarded as indispensable to the maintenance of unity and harmony in the familyofChrist. Ishallonlysay,thatitwill be time enough to provide for this new order ofthingswhen itshallarrive;andthat,inthe mean while,in the present state of the world, I should as soon think of extending and edi
fying the Church, by laying aside all the meansofgrace;asofpromotingitspurityand peace,by abandoning those methods of bind ing its members together, which have been
found necessary ever since the days of the Apostles.

 cause your adversary,the Devil,as a roaring lion goeth about seeking whom he may de
And another apostle,reminded those towhom hewrote,thatthisadversaryoften times “ transformed himself into an angel of light.” So it was eighteen centuries ago; andsoitisatthishour. Theveryblessings oftheChurch,astheyhave been inallages, so they are now, converted into means of deception. The progressive harmony of the different evangelical denominations; their in creasing zeal for the spread of the Gospel; their growing disposition to sacrifice many smaller differences on the altar of our c o m m o n
Christianity; have so fired the imaginations of some ardent, sanguine spirits, that they have allowed themselves to be hurried on to
the unwarranted conclusion, that all former
rules were about to be laid aside,and all for mer barriers to be broken down.
member my young friends, that a similar notion has been entertained, and afterwards
abandoned , in almost every century since the incarnation of Christ. Remember, too, that
even when the Millennium shall arrive,human nature will still be depraved, and will still
 116 UTILITY AND IMPORTANCE
vour
.”
But re

 OF CREEDS AND CONFESSIONS. 117
While Iexhort you,then,to hailwith de
light the spirit of harmony,of union,and of
active co-operation,which is among the most precious and animating “ signs of the times" in which we live; and while I earnestly hope
that no student of this Seminary will ever s t a n d a f a r o f f, o r t u r n a w a y w i t h a n e v i l e y e ,
when the true standard of Christ israised by any denomination; let me,at the same time,
intreat you always to temper your zeal with soberness. I say soberness; for this is a
quality,not always found associated even with
great vigour of talent, and great warmth of piety. Many a man of admirable endow
ments in other respects; endowments which qualified him, if they had been happily di
 stand in need of law and regulation,not,per haps,asmuch,butasreallyasnow. And, finally,rememberthatbefore thatblessedday
shallactuallydawn upon ourworld,we shall probably have m a n y a sore conflict with the enemies oftruth,and stand inneed ofallthose methodsofdistinguishingandbindingtogether its friends, to which the word of God,and
uniform experience have so long given their sanction .

 TheChurchisstillin thewilderness;"
and every age has its appropriate trials.
Among thoseof the presentday,isaspiritof
restless innovation ; a disposition to consider
every thing that is new as of course an im
provement. Happy are they, who, taking
the word of God for their guide,and walking
in “ the footsteps of the flock," continually seek the purity,the peace,and the edification
of the Master's family :- W h o ,listening with more respect to the unerring Oracle, and to the sober lessons ofChristian experience,than to the delusions of fashionable error, hold on
theirway,“turning neithertotherighthand
 118 UTILITY AND IMPORTANCE
rected, to adorn and bless the Church ; has been either so transported by the visions of a
heated fancy; or so deceived by keeping his eye fixed on a single point only of the vast scene before him; or so impelled by the ap proaches of others, as anomalous as himself;
that,like the comet of the infidel philosopher, he has only been able to strike off a few wan deringstarsfrom the parent luminary,while he himself, given up to an orbit more and more eccentric,never returned,either to regu larity or usefulness.

 OF CREEDS AND CONFESSIONS.
119
northeleft,” andconsideringitastheirhigh est honour and happiness to be employed as
humble, peaceful instruments in building up
that “ kingdom which is not meat and drink,
but righteousness, and peace, and joy in the
Holy Ghost!” May God grant to each of us thisbestofallhonours!And tohisnamebe
the praise, for ever ! A m e n !